
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Country
 * 
 */
export type Country = Prisma.CountryModel
/**
 * Model CountryState
 * 
 */
export type CountryState = Prisma.CountryStateModel
/**
 * Model McpOAuthClient
 * 
 */
export type McpOAuthClient = Prisma.McpOAuthClientModel
/**
 * Model McpOAuthCode
 * 
 */
export type McpOAuthCode = Prisma.McpOAuthCodeModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model Sell
 * 
 */
export type Sell = Prisma.SellModel
/**
 * Model Stock
 * 
 */
export type Stock = Prisma.StockModel
/**
 * Model StockTransaction
 * 
 */
export type StockTransaction = Prisma.StockTransactionModel
/**
 * Model Store
 * 
 */
export type Store = Prisma.StoreModel
/**
 * Model Subcategory
 * 
 */
export type Subcategory = Prisma.SubcategoryModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model UserSession
 * 
 */
export type UserSession = Prisma.UserSessionModel
/**
 * Model Warehouse
 * 
 */
export type Warehouse = Prisma.WarehouseModel
