
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TransactionStatus = {
  PENDING: 'PENDING',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED'
} as const

export type TransactionStatus = (typeof TransactionStatus)[keyof typeof TransactionStatus]


export const Role = {
  SUPERUSER: 'SUPERUSER',
  GUEST: 'GUEST',
  STORE_MANAGER: 'STORE_MANAGER',
  STAFF: 'STAFF',
  CUSTOMER: 'CUSTOMER'
} as const

export type Role = (typeof Role)[keyof typeof Role]
