
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CountryState` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CountryState
 * 
 */
export type CountryStateModel = runtime.Types.Result.DefaultSelection<Prisma.$CountryStatePayload>

export type AggregateCountryState = {
  _count: CountryStateCountAggregateOutputType | null
  _min: CountryStateMinAggregateOutputType | null
  _max: CountryStateMaxAggregateOutputType | null
}

export type CountryStateMinAggregateOutputType = {
  id: string | null
  name: string | null
  countryId: string | null
  subdivisionCode: string | null
  tz: string | null
  flag: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CountryStateMaxAggregateOutputType = {
  id: string | null
  name: string | null
  countryId: string | null
  subdivisionCode: string | null
  tz: string | null
  flag: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CountryStateCountAggregateOutputType = {
  id: number
  name: number
  countryId: number
  subdivisionCode: number
  tz: number
  flag: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CountryStateMinAggregateInputType = {
  id?: true
  name?: true
  countryId?: true
  subdivisionCode?: true
  tz?: true
  flag?: true
  createdAt?: true
  updatedAt?: true
}

export type CountryStateMaxAggregateInputType = {
  id?: true
  name?: true
  countryId?: true
  subdivisionCode?: true
  tz?: true
  flag?: true
  createdAt?: true
  updatedAt?: true
}

export type CountryStateCountAggregateInputType = {
  id?: true
  name?: true
  countryId?: true
  subdivisionCode?: true
  tz?: true
  flag?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CountryStateAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CountryState to aggregate.
   */
  where?: Prisma.CountryStateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CountryStates to fetch.
   */
  orderBy?: Prisma.CountryStateOrderByWithRelationInput | Prisma.CountryStateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CountryStateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CountryStates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CountryStates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CountryStates
  **/
  _count?: true | CountryStateCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CountryStateMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CountryStateMaxAggregateInputType
}

export type GetCountryStateAggregateType<T extends CountryStateAggregateArgs> = {
      [P in keyof T & keyof AggregateCountryState]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCountryState[P]>
    : Prisma.GetScalarType<T[P], AggregateCountryState[P]>
}




export type CountryStateGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CountryStateWhereInput
  orderBy?: Prisma.CountryStateOrderByWithAggregationInput | Prisma.CountryStateOrderByWithAggregationInput[]
  by: Prisma.CountryStateScalarFieldEnum[] | Prisma.CountryStateScalarFieldEnum
  having?: Prisma.CountryStateScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CountryStateCountAggregateInputType | true
  _min?: CountryStateMinAggregateInputType
  _max?: CountryStateMaxAggregateInputType
}

export type CountryStateGroupByOutputType = {
  id: string
  name: string
  countryId: string
  subdivisionCode: string
  tz: string | null
  flag: string | null
  createdAt: Date
  updatedAt: Date
  _count: CountryStateCountAggregateOutputType | null
  _min: CountryStateMinAggregateOutputType | null
  _max: CountryStateMaxAggregateOutputType | null
}

export type GetCountryStateGroupByPayload<T extends CountryStateGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CountryStateGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CountryStateGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CountryStateGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CountryStateGroupByOutputType[P]>
      }
    >
  >



export type CountryStateWhereInput = {
  AND?: Prisma.CountryStateWhereInput | Prisma.CountryStateWhereInput[]
  OR?: Prisma.CountryStateWhereInput[]
  NOT?: Prisma.CountryStateWhereInput | Prisma.CountryStateWhereInput[]
  id?: Prisma.UuidFilter<"CountryState"> | string
  name?: Prisma.StringFilter<"CountryState"> | string
  countryId?: Prisma.UuidFilter<"CountryState"> | string
  subdivisionCode?: Prisma.StringFilter<"CountryState"> | string
  tz?: Prisma.StringNullableFilter<"CountryState"> | string | null
  flag?: Prisma.StringNullableFilter<"CountryState"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CountryState"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CountryState"> | Date | string
  country?: Prisma.XOR<Prisma.CountryScalarRelationFilter, Prisma.CountryWhereInput>
  users?: Prisma.UserListRelationFilter
  stores?: Prisma.StoreListRelationFilter
  warehouses?: Prisma.WarehouseListRelationFilter
}

export type CountryStateOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  countryId?: Prisma.SortOrder
  subdivisionCode?: Prisma.SortOrder
  tz?: Prisma.SortOrderInput | Prisma.SortOrder
  flag?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  country?: Prisma.CountryOrderByWithRelationInput
  users?: Prisma.UserOrderByRelationAggregateInput
  stores?: Prisma.StoreOrderByRelationAggregateInput
  warehouses?: Prisma.WarehouseOrderByRelationAggregateInput
}

export type CountryStateWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CountryStateWhereInput | Prisma.CountryStateWhereInput[]
  OR?: Prisma.CountryStateWhereInput[]
  NOT?: Prisma.CountryStateWhereInput | Prisma.CountryStateWhereInput[]
  name?: Prisma.StringFilter<"CountryState"> | string
  countryId?: Prisma.UuidFilter<"CountryState"> | string
  subdivisionCode?: Prisma.StringFilter<"CountryState"> | string
  tz?: Prisma.StringNullableFilter<"CountryState"> | string | null
  flag?: Prisma.StringNullableFilter<"CountryState"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CountryState"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CountryState"> | Date | string
  country?: Prisma.XOR<Prisma.CountryScalarRelationFilter, Prisma.CountryWhereInput>
  users?: Prisma.UserListRelationFilter
  stores?: Prisma.StoreListRelationFilter
  warehouses?: Prisma.WarehouseListRelationFilter
}, "id">

export type CountryStateOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  countryId?: Prisma.SortOrder
  subdivisionCode?: Prisma.SortOrder
  tz?: Prisma.SortOrderInput | Prisma.SortOrder
  flag?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CountryStateCountOrderByAggregateInput
  _max?: Prisma.CountryStateMaxOrderByAggregateInput
  _min?: Prisma.CountryStateMinOrderByAggregateInput
}

export type CountryStateScalarWhereWithAggregatesInput = {
  AND?: Prisma.CountryStateScalarWhereWithAggregatesInput | Prisma.CountryStateScalarWhereWithAggregatesInput[]
  OR?: Prisma.CountryStateScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CountryStateScalarWhereWithAggregatesInput | Prisma.CountryStateScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"CountryState"> | string
  name?: Prisma.StringWithAggregatesFilter<"CountryState"> | string
  countryId?: Prisma.UuidWithAggregatesFilter<"CountryState"> | string
  subdivisionCode?: Prisma.StringWithAggregatesFilter<"CountryState"> | string
  tz?: Prisma.StringNullableWithAggregatesFilter<"CountryState"> | string | null
  flag?: Prisma.StringNullableWithAggregatesFilter<"CountryState"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CountryState"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CountryState"> | Date | string
}

export type CountryStateCreateInput = {
  id?: string
  name: string
  subdivisionCode: string
  tz?: string | null
  flag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  country: Prisma.CountryCreateNestedOneWithoutStatesInput
  users?: Prisma.UserCreateNestedManyWithoutStateInput
  stores?: Prisma.StoreCreateNestedManyWithoutStateInput
  warehouses?: Prisma.WarehouseCreateNestedManyWithoutStateInput
}

export type CountryStateUncheckedCreateInput = {
  id?: string
  name: string
  countryId: string
  subdivisionCode: string
  tz?: string | null
  flag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutStateInput
  stores?: Prisma.StoreUncheckedCreateNestedManyWithoutStateInput
  warehouses?: Prisma.WarehouseUncheckedCreateNestedManyWithoutStateInput
}

export type CountryStateUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subdivisionCode?: Prisma.StringFieldUpdateOperationsInput | string
  tz?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  flag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  country?: Prisma.CountryUpdateOneRequiredWithoutStatesNestedInput
  users?: Prisma.UserUpdateManyWithoutStateNestedInput
  stores?: Prisma.StoreUpdateManyWithoutStateNestedInput
  warehouses?: Prisma.WarehouseUpdateManyWithoutStateNestedInput
}

export type CountryStateUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  countryId?: Prisma.StringFieldUpdateOperationsInput | string
  subdivisionCode?: Prisma.StringFieldUpdateOperationsInput | string
  tz?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  flag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutStateNestedInput
  stores?: Prisma.StoreUncheckedUpdateManyWithoutStateNestedInput
  warehouses?: Prisma.WarehouseUncheckedUpdateManyWithoutStateNestedInput
}

export type CountryStateCreateManyInput = {
  id?: string
  name: string
  countryId: string
  subdivisionCode: string
  tz?: string | null
  flag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CountryStateUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subdivisionCode?: Prisma.StringFieldUpdateOperationsInput | string
  tz?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  flag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CountryStateUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  countryId?: Prisma.StringFieldUpdateOperationsInput | string
  subdivisionCode?: Prisma.StringFieldUpdateOperationsInput | string
  tz?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  flag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CountryStateListRelationFilter = {
  every?: Prisma.CountryStateWhereInput
  some?: Prisma.CountryStateWhereInput
  none?: Prisma.CountryStateWhereInput
}

export type CountryStateOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CountryStateCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  countryId?: Prisma.SortOrder
  subdivisionCode?: Prisma.SortOrder
  tz?: Prisma.SortOrder
  flag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CountryStateMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  countryId?: Prisma.SortOrder
  subdivisionCode?: Prisma.SortOrder
  tz?: Prisma.SortOrder
  flag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CountryStateMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  countryId?: Prisma.SortOrder
  subdivisionCode?: Prisma.SortOrder
  tz?: Prisma.SortOrder
  flag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CountryStateScalarRelationFilter = {
  is?: Prisma.CountryStateWhereInput
  isNot?: Prisma.CountryStateWhereInput
}

export type CountryStateNullableScalarRelationFilter = {
  is?: Prisma.CountryStateWhereInput | null
  isNot?: Prisma.CountryStateWhereInput | null
}

export type CountryStateCreateNestedManyWithoutCountryInput = {
  create?: Prisma.XOR<Prisma.CountryStateCreateWithoutCountryInput, Prisma.CountryStateUncheckedCreateWithoutCountryInput> | Prisma.CountryStateCreateWithoutCountryInput[] | Prisma.CountryStateUncheckedCreateWithoutCountryInput[]
  connectOrCreate?: Prisma.CountryStateCreateOrConnectWithoutCountryInput | Prisma.CountryStateCreateOrConnectWithoutCountryInput[]
  createMany?: Prisma.CountryStateCreateManyCountryInputEnvelope
  connect?: Prisma.CountryStateWhereUniqueInput | Prisma.CountryStateWhereUniqueInput[]
}

export type CountryStateUncheckedCreateNestedManyWithoutCountryInput = {
  create?: Prisma.XOR<Prisma.CountryStateCreateWithoutCountryInput, Prisma.CountryStateUncheckedCreateWithoutCountryInput> | Prisma.CountryStateCreateWithoutCountryInput[] | Prisma.CountryStateUncheckedCreateWithoutCountryInput[]
  connectOrCreate?: Prisma.CountryStateCreateOrConnectWithoutCountryInput | Prisma.CountryStateCreateOrConnectWithoutCountryInput[]
  createMany?: Prisma.CountryStateCreateManyCountryInputEnvelope
  connect?: Prisma.CountryStateWhereUniqueInput | Prisma.CountryStateWhereUniqueInput[]
}

export type CountryStateUpdateManyWithoutCountryNestedInput = {
  create?: Prisma.XOR<Prisma.CountryStateCreateWithoutCountryInput, Prisma.CountryStateUncheckedCreateWithoutCountryInput> | Prisma.CountryStateCreateWithoutCountryInput[] | Prisma.CountryStateUncheckedCreateWithoutCountryInput[]
  connectOrCreate?: Prisma.CountryStateCreateOrConnectWithoutCountryInput | Prisma.CountryStateCreateOrConnectWithoutCountryInput[]
  upsert?: Prisma.CountryStateUpsertWithWhereUniqueWithoutCountryInput | Prisma.CountryStateUpsertWithWhereUniqueWithoutCountryInput[]
  createMany?: Prisma.CountryStateCreateManyCountryInputEnvelope
  set?: Prisma.CountryStateWhereUniqueInput | Prisma.CountryStateWhereUniqueInput[]
  disconnect?: Prisma.CountryStateWhereUniqueInput | Prisma.CountryStateWhereUniqueInput[]
  delete?: Prisma.CountryStateWhereUniqueInput | Prisma.CountryStateWhereUniqueInput[]
  connect?: Prisma.CountryStateWhereUniqueInput | Prisma.CountryStateWhereUniqueInput[]
  update?: Prisma.CountryStateUpdateWithWhereUniqueWithoutCountryInput | Prisma.CountryStateUpdateWithWhereUniqueWithoutCountryInput[]
  updateMany?: Prisma.CountryStateUpdateManyWithWhereWithoutCountryInput | Prisma.CountryStateUpdateManyWithWhereWithoutCountryInput[]
  deleteMany?: Prisma.CountryStateScalarWhereInput | Prisma.CountryStateScalarWhereInput[]
}

export type CountryStateUncheckedUpdateManyWithoutCountryNestedInput = {
  create?: Prisma.XOR<Prisma.CountryStateCreateWithoutCountryInput, Prisma.CountryStateUncheckedCreateWithoutCountryInput> | Prisma.CountryStateCreateWithoutCountryInput[] | Prisma.CountryStateUncheckedCreateWithoutCountryInput[]
  connectOrCreate?: Prisma.CountryStateCreateOrConnectWithoutCountryInput | Prisma.CountryStateCreateOrConnectWithoutCountryInput[]
  upsert?: Prisma.CountryStateUpsertWithWhereUniqueWithoutCountryInput | Prisma.CountryStateUpsertWithWhereUniqueWithoutCountryInput[]
  createMany?: Prisma.CountryStateCreateManyCountryInputEnvelope
  set?: Prisma.CountryStateWhereUniqueInput | Prisma.CountryStateWhereUniqueInput[]
  disconnect?: Prisma.CountryStateWhereUniqueInput | Prisma.CountryStateWhereUniqueInput[]
  delete?: Prisma.CountryStateWhereUniqueInput | Prisma.CountryStateWhereUniqueInput[]
  connect?: Prisma.CountryStateWhereUniqueInput | Prisma.CountryStateWhereUniqueInput[]
  update?: Prisma.CountryStateUpdateWithWhereUniqueWithoutCountryInput | Prisma.CountryStateUpdateWithWhereUniqueWithoutCountryInput[]
  updateMany?: Prisma.CountryStateUpdateManyWithWhereWithoutCountryInput | Prisma.CountryStateUpdateManyWithWhereWithoutCountryInput[]
  deleteMany?: Prisma.CountryStateScalarWhereInput | Prisma.CountryStateScalarWhereInput[]
}

export type CountryStateCreateNestedOneWithoutStoresInput = {
  create?: Prisma.XOR<Prisma.CountryStateCreateWithoutStoresInput, Prisma.CountryStateUncheckedCreateWithoutStoresInput>
  connectOrCreate?: Prisma.CountryStateCreateOrConnectWithoutStoresInput
  connect?: Prisma.CountryStateWhereUniqueInput
}

export type CountryStateUpdateOneRequiredWithoutStoresNestedInput = {
  create?: Prisma.XOR<Prisma.CountryStateCreateWithoutStoresInput, Prisma.CountryStateUncheckedCreateWithoutStoresInput>
  connectOrCreate?: Prisma.CountryStateCreateOrConnectWithoutStoresInput
  upsert?: Prisma.CountryStateUpsertWithoutStoresInput
  connect?: Prisma.CountryStateWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CountryStateUpdateToOneWithWhereWithoutStoresInput, Prisma.CountryStateUpdateWithoutStoresInput>, Prisma.CountryStateUncheckedUpdateWithoutStoresInput>
}

export type CountryStateCreateNestedOneWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.CountryStateCreateWithoutUsersInput, Prisma.CountryStateUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.CountryStateCreateOrConnectWithoutUsersInput
  connect?: Prisma.CountryStateWhereUniqueInput
}

export type CountryStateUpdateOneWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.CountryStateCreateWithoutUsersInput, Prisma.CountryStateUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.CountryStateCreateOrConnectWithoutUsersInput
  upsert?: Prisma.CountryStateUpsertWithoutUsersInput
  disconnect?: Prisma.CountryStateWhereInput | boolean
  delete?: Prisma.CountryStateWhereInput | boolean
  connect?: Prisma.CountryStateWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CountryStateUpdateToOneWithWhereWithoutUsersInput, Prisma.CountryStateUpdateWithoutUsersInput>, Prisma.CountryStateUncheckedUpdateWithoutUsersInput>
}

export type CountryStateCreateNestedOneWithoutWarehousesInput = {
  create?: Prisma.XOR<Prisma.CountryStateCreateWithoutWarehousesInput, Prisma.CountryStateUncheckedCreateWithoutWarehousesInput>
  connectOrCreate?: Prisma.CountryStateCreateOrConnectWithoutWarehousesInput
  connect?: Prisma.CountryStateWhereUniqueInput
}

export type CountryStateUpdateOneRequiredWithoutWarehousesNestedInput = {
  create?: Prisma.XOR<Prisma.CountryStateCreateWithoutWarehousesInput, Prisma.CountryStateUncheckedCreateWithoutWarehousesInput>
  connectOrCreate?: Prisma.CountryStateCreateOrConnectWithoutWarehousesInput
  upsert?: Prisma.CountryStateUpsertWithoutWarehousesInput
  connect?: Prisma.CountryStateWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CountryStateUpdateToOneWithWhereWithoutWarehousesInput, Prisma.CountryStateUpdateWithoutWarehousesInput>, Prisma.CountryStateUncheckedUpdateWithoutWarehousesInput>
}

export type CountryStateCreateWithoutCountryInput = {
  id?: string
  name: string
  subdivisionCode: string
  tz?: string | null
  flag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserCreateNestedManyWithoutStateInput
  stores?: Prisma.StoreCreateNestedManyWithoutStateInput
  warehouses?: Prisma.WarehouseCreateNestedManyWithoutStateInput
}

export type CountryStateUncheckedCreateWithoutCountryInput = {
  id?: string
  name: string
  subdivisionCode: string
  tz?: string | null
  flag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutStateInput
  stores?: Prisma.StoreUncheckedCreateNestedManyWithoutStateInput
  warehouses?: Prisma.WarehouseUncheckedCreateNestedManyWithoutStateInput
}

export type CountryStateCreateOrConnectWithoutCountryInput = {
  where: Prisma.CountryStateWhereUniqueInput
  create: Prisma.XOR<Prisma.CountryStateCreateWithoutCountryInput, Prisma.CountryStateUncheckedCreateWithoutCountryInput>
}

export type CountryStateCreateManyCountryInputEnvelope = {
  data: Prisma.CountryStateCreateManyCountryInput | Prisma.CountryStateCreateManyCountryInput[]
  skipDuplicates?: boolean
}

export type CountryStateUpsertWithWhereUniqueWithoutCountryInput = {
  where: Prisma.CountryStateWhereUniqueInput
  update: Prisma.XOR<Prisma.CountryStateUpdateWithoutCountryInput, Prisma.CountryStateUncheckedUpdateWithoutCountryInput>
  create: Prisma.XOR<Prisma.CountryStateCreateWithoutCountryInput, Prisma.CountryStateUncheckedCreateWithoutCountryInput>
}

export type CountryStateUpdateWithWhereUniqueWithoutCountryInput = {
  where: Prisma.CountryStateWhereUniqueInput
  data: Prisma.XOR<Prisma.CountryStateUpdateWithoutCountryInput, Prisma.CountryStateUncheckedUpdateWithoutCountryInput>
}

export type CountryStateUpdateManyWithWhereWithoutCountryInput = {
  where: Prisma.CountryStateScalarWhereInput
  data: Prisma.XOR<Prisma.CountryStateUpdateManyMutationInput, Prisma.CountryStateUncheckedUpdateManyWithoutCountryInput>
}

export type CountryStateScalarWhereInput = {
  AND?: Prisma.CountryStateScalarWhereInput | Prisma.CountryStateScalarWhereInput[]
  OR?: Prisma.CountryStateScalarWhereInput[]
  NOT?: Prisma.CountryStateScalarWhereInput | Prisma.CountryStateScalarWhereInput[]
  id?: Prisma.UuidFilter<"CountryState"> | string
  name?: Prisma.StringFilter<"CountryState"> | string
  countryId?: Prisma.UuidFilter<"CountryState"> | string
  subdivisionCode?: Prisma.StringFilter<"CountryState"> | string
  tz?: Prisma.StringNullableFilter<"CountryState"> | string | null
  flag?: Prisma.StringNullableFilter<"CountryState"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CountryState"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CountryState"> | Date | string
}

export type CountryStateCreateWithoutStoresInput = {
  id?: string
  name: string
  subdivisionCode: string
  tz?: string | null
  flag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  country: Prisma.CountryCreateNestedOneWithoutStatesInput
  users?: Prisma.UserCreateNestedManyWithoutStateInput
  warehouses?: Prisma.WarehouseCreateNestedManyWithoutStateInput
}

export type CountryStateUncheckedCreateWithoutStoresInput = {
  id?: string
  name: string
  countryId: string
  subdivisionCode: string
  tz?: string | null
  flag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutStateInput
  warehouses?: Prisma.WarehouseUncheckedCreateNestedManyWithoutStateInput
}

export type CountryStateCreateOrConnectWithoutStoresInput = {
  where: Prisma.CountryStateWhereUniqueInput
  create: Prisma.XOR<Prisma.CountryStateCreateWithoutStoresInput, Prisma.CountryStateUncheckedCreateWithoutStoresInput>
}

export type CountryStateUpsertWithoutStoresInput = {
  update: Prisma.XOR<Prisma.CountryStateUpdateWithoutStoresInput, Prisma.CountryStateUncheckedUpdateWithoutStoresInput>
  create: Prisma.XOR<Prisma.CountryStateCreateWithoutStoresInput, Prisma.CountryStateUncheckedCreateWithoutStoresInput>
  where?: Prisma.CountryStateWhereInput
}

export type CountryStateUpdateToOneWithWhereWithoutStoresInput = {
  where?: Prisma.CountryStateWhereInput
  data: Prisma.XOR<Prisma.CountryStateUpdateWithoutStoresInput, Prisma.CountryStateUncheckedUpdateWithoutStoresInput>
}

export type CountryStateUpdateWithoutStoresInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subdivisionCode?: Prisma.StringFieldUpdateOperationsInput | string
  tz?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  flag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  country?: Prisma.CountryUpdateOneRequiredWithoutStatesNestedInput
  users?: Prisma.UserUpdateManyWithoutStateNestedInput
  warehouses?: Prisma.WarehouseUpdateManyWithoutStateNestedInput
}

export type CountryStateUncheckedUpdateWithoutStoresInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  countryId?: Prisma.StringFieldUpdateOperationsInput | string
  subdivisionCode?: Prisma.StringFieldUpdateOperationsInput | string
  tz?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  flag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutStateNestedInput
  warehouses?: Prisma.WarehouseUncheckedUpdateManyWithoutStateNestedInput
}

export type CountryStateCreateWithoutUsersInput = {
  id?: string
  name: string
  subdivisionCode: string
  tz?: string | null
  flag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  country: Prisma.CountryCreateNestedOneWithoutStatesInput
  stores?: Prisma.StoreCreateNestedManyWithoutStateInput
  warehouses?: Prisma.WarehouseCreateNestedManyWithoutStateInput
}

export type CountryStateUncheckedCreateWithoutUsersInput = {
  id?: string
  name: string
  countryId: string
  subdivisionCode: string
  tz?: string | null
  flag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  stores?: Prisma.StoreUncheckedCreateNestedManyWithoutStateInput
  warehouses?: Prisma.WarehouseUncheckedCreateNestedManyWithoutStateInput
}

export type CountryStateCreateOrConnectWithoutUsersInput = {
  where: Prisma.CountryStateWhereUniqueInput
  create: Prisma.XOR<Prisma.CountryStateCreateWithoutUsersInput, Prisma.CountryStateUncheckedCreateWithoutUsersInput>
}

export type CountryStateUpsertWithoutUsersInput = {
  update: Prisma.XOR<Prisma.CountryStateUpdateWithoutUsersInput, Prisma.CountryStateUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.CountryStateCreateWithoutUsersInput, Prisma.CountryStateUncheckedCreateWithoutUsersInput>
  where?: Prisma.CountryStateWhereInput
}

export type CountryStateUpdateToOneWithWhereWithoutUsersInput = {
  where?: Prisma.CountryStateWhereInput
  data: Prisma.XOR<Prisma.CountryStateUpdateWithoutUsersInput, Prisma.CountryStateUncheckedUpdateWithoutUsersInput>
}

export type CountryStateUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subdivisionCode?: Prisma.StringFieldUpdateOperationsInput | string
  tz?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  flag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  country?: Prisma.CountryUpdateOneRequiredWithoutStatesNestedInput
  stores?: Prisma.StoreUpdateManyWithoutStateNestedInput
  warehouses?: Prisma.WarehouseUpdateManyWithoutStateNestedInput
}

export type CountryStateUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  countryId?: Prisma.StringFieldUpdateOperationsInput | string
  subdivisionCode?: Prisma.StringFieldUpdateOperationsInput | string
  tz?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  flag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  stores?: Prisma.StoreUncheckedUpdateManyWithoutStateNestedInput
  warehouses?: Prisma.WarehouseUncheckedUpdateManyWithoutStateNestedInput
}

export type CountryStateCreateWithoutWarehousesInput = {
  id?: string
  name: string
  subdivisionCode: string
  tz?: string | null
  flag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  country: Prisma.CountryCreateNestedOneWithoutStatesInput
  users?: Prisma.UserCreateNestedManyWithoutStateInput
  stores?: Prisma.StoreCreateNestedManyWithoutStateInput
}

export type CountryStateUncheckedCreateWithoutWarehousesInput = {
  id?: string
  name: string
  countryId: string
  subdivisionCode: string
  tz?: string | null
  flag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutStateInput
  stores?: Prisma.StoreUncheckedCreateNestedManyWithoutStateInput
}

export type CountryStateCreateOrConnectWithoutWarehousesInput = {
  where: Prisma.CountryStateWhereUniqueInput
  create: Prisma.XOR<Prisma.CountryStateCreateWithoutWarehousesInput, Prisma.CountryStateUncheckedCreateWithoutWarehousesInput>
}

export type CountryStateUpsertWithoutWarehousesInput = {
  update: Prisma.XOR<Prisma.CountryStateUpdateWithoutWarehousesInput, Prisma.CountryStateUncheckedUpdateWithoutWarehousesInput>
  create: Prisma.XOR<Prisma.CountryStateCreateWithoutWarehousesInput, Prisma.CountryStateUncheckedCreateWithoutWarehousesInput>
  where?: Prisma.CountryStateWhereInput
}

export type CountryStateUpdateToOneWithWhereWithoutWarehousesInput = {
  where?: Prisma.CountryStateWhereInput
  data: Prisma.XOR<Prisma.CountryStateUpdateWithoutWarehousesInput, Prisma.CountryStateUncheckedUpdateWithoutWarehousesInput>
}

export type CountryStateUpdateWithoutWarehousesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subdivisionCode?: Prisma.StringFieldUpdateOperationsInput | string
  tz?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  flag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  country?: Prisma.CountryUpdateOneRequiredWithoutStatesNestedInput
  users?: Prisma.UserUpdateManyWithoutStateNestedInput
  stores?: Prisma.StoreUpdateManyWithoutStateNestedInput
}

export type CountryStateUncheckedUpdateWithoutWarehousesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  countryId?: Prisma.StringFieldUpdateOperationsInput | string
  subdivisionCode?: Prisma.StringFieldUpdateOperationsInput | string
  tz?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  flag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutStateNestedInput
  stores?: Prisma.StoreUncheckedUpdateManyWithoutStateNestedInput
}

export type CountryStateCreateManyCountryInput = {
  id?: string
  name: string
  subdivisionCode: string
  tz?: string | null
  flag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CountryStateUpdateWithoutCountryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subdivisionCode?: Prisma.StringFieldUpdateOperationsInput | string
  tz?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  flag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUpdateManyWithoutStateNestedInput
  stores?: Prisma.StoreUpdateManyWithoutStateNestedInput
  warehouses?: Prisma.WarehouseUpdateManyWithoutStateNestedInput
}

export type CountryStateUncheckedUpdateWithoutCountryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subdivisionCode?: Prisma.StringFieldUpdateOperationsInput | string
  tz?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  flag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UserUncheckedUpdateManyWithoutStateNestedInput
  stores?: Prisma.StoreUncheckedUpdateManyWithoutStateNestedInput
  warehouses?: Prisma.WarehouseUncheckedUpdateManyWithoutStateNestedInput
}

export type CountryStateUncheckedUpdateManyWithoutCountryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  subdivisionCode?: Prisma.StringFieldUpdateOperationsInput | string
  tz?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  flag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type CountryStateCountOutputType
 */

export type CountryStateCountOutputType = {
  users: number
  stores: number
  warehouses: number
}

export type CountryStateCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | CountryStateCountOutputTypeCountUsersArgs
  stores?: boolean | CountryStateCountOutputTypeCountStoresArgs
  warehouses?: boolean | CountryStateCountOutputTypeCountWarehousesArgs
}

/**
 * CountryStateCountOutputType without action
 */
export type CountryStateCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryStateCountOutputType
   */
  select?: Prisma.CountryStateCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CountryStateCountOutputType without action
 */
export type CountryStateCountOutputTypeCountUsersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
}

/**
 * CountryStateCountOutputType without action
 */
export type CountryStateCountOutputTypeCountStoresArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StoreWhereInput
}

/**
 * CountryStateCountOutputType without action
 */
export type CountryStateCountOutputTypeCountWarehousesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WarehouseWhereInput
}


export type CountryStateSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  countryId?: boolean
  subdivisionCode?: boolean
  tz?: boolean
  flag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  country?: boolean | Prisma.CountryDefaultArgs<ExtArgs>
  users?: boolean | Prisma.CountryState$usersArgs<ExtArgs>
  stores?: boolean | Prisma.CountryState$storesArgs<ExtArgs>
  warehouses?: boolean | Prisma.CountryState$warehousesArgs<ExtArgs>
  _count?: boolean | Prisma.CountryStateCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["countryState"]>

export type CountryStateSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  countryId?: boolean
  subdivisionCode?: boolean
  tz?: boolean
  flag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  country?: boolean | Prisma.CountryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["countryState"]>

export type CountryStateSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  countryId?: boolean
  subdivisionCode?: boolean
  tz?: boolean
  flag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  country?: boolean | Prisma.CountryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["countryState"]>

export type CountryStateSelectScalar = {
  id?: boolean
  name?: boolean
  countryId?: boolean
  subdivisionCode?: boolean
  tz?: boolean
  flag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CountryStateOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "countryId" | "subdivisionCode" | "tz" | "flag" | "createdAt" | "updatedAt", ExtArgs["result"]["countryState"]>
export type CountryStateInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  country?: boolean | Prisma.CountryDefaultArgs<ExtArgs>
  users?: boolean | Prisma.CountryState$usersArgs<ExtArgs>
  stores?: boolean | Prisma.CountryState$storesArgs<ExtArgs>
  warehouses?: boolean | Prisma.CountryState$warehousesArgs<ExtArgs>
  _count?: boolean | Prisma.CountryStateCountOutputTypeDefaultArgs<ExtArgs>
}
export type CountryStateIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  country?: boolean | Prisma.CountryDefaultArgs<ExtArgs>
}
export type CountryStateIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  country?: boolean | Prisma.CountryDefaultArgs<ExtArgs>
}

export type $CountryStatePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CountryState"
  objects: {
    country: Prisma.$CountryPayload<ExtArgs>
    users: Prisma.$UserPayload<ExtArgs>[]
    stores: Prisma.$StorePayload<ExtArgs>[]
    warehouses: Prisma.$WarehousePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    countryId: string
    subdivisionCode: string
    tz: string | null
    flag: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["countryState"]>
  composites: {}
}

export type CountryStateGetPayload<S extends boolean | null | undefined | CountryStateDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CountryStatePayload, S>

export type CountryStateCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CountryStateFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CountryStateCountAggregateInputType | true
  }

export interface CountryStateDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CountryState'], meta: { name: 'CountryState' } }
  /**
   * Find zero or one CountryState that matches the filter.
   * @param {CountryStateFindUniqueArgs} args - Arguments to find a CountryState
   * @example
   * // Get one CountryState
   * const countryState = await prisma.countryState.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CountryStateFindUniqueArgs>(args: Prisma.SelectSubset<T, CountryStateFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CountryStateClient<runtime.Types.Result.GetResult<Prisma.$CountryStatePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CountryState that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CountryStateFindUniqueOrThrowArgs} args - Arguments to find a CountryState
   * @example
   * // Get one CountryState
   * const countryState = await prisma.countryState.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CountryStateFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CountryStateFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CountryStateClient<runtime.Types.Result.GetResult<Prisma.$CountryStatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CountryState that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryStateFindFirstArgs} args - Arguments to find a CountryState
   * @example
   * // Get one CountryState
   * const countryState = await prisma.countryState.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CountryStateFindFirstArgs>(args?: Prisma.SelectSubset<T, CountryStateFindFirstArgs<ExtArgs>>): Prisma.Prisma__CountryStateClient<runtime.Types.Result.GetResult<Prisma.$CountryStatePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CountryState that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryStateFindFirstOrThrowArgs} args - Arguments to find a CountryState
   * @example
   * // Get one CountryState
   * const countryState = await prisma.countryState.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CountryStateFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CountryStateFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CountryStateClient<runtime.Types.Result.GetResult<Prisma.$CountryStatePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CountryStates that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryStateFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CountryStates
   * const countryStates = await prisma.countryState.findMany()
   * 
   * // Get first 10 CountryStates
   * const countryStates = await prisma.countryState.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const countryStateWithIdOnly = await prisma.countryState.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CountryStateFindManyArgs>(args?: Prisma.SelectSubset<T, CountryStateFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CountryStatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CountryState.
   * @param {CountryStateCreateArgs} args - Arguments to create a CountryState.
   * @example
   * // Create one CountryState
   * const CountryState = await prisma.countryState.create({
   *   data: {
   *     // ... data to create a CountryState
   *   }
   * })
   * 
   */
  create<T extends CountryStateCreateArgs>(args: Prisma.SelectSubset<T, CountryStateCreateArgs<ExtArgs>>): Prisma.Prisma__CountryStateClient<runtime.Types.Result.GetResult<Prisma.$CountryStatePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CountryStates.
   * @param {CountryStateCreateManyArgs} args - Arguments to create many CountryStates.
   * @example
   * // Create many CountryStates
   * const countryState = await prisma.countryState.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CountryStateCreateManyArgs>(args?: Prisma.SelectSubset<T, CountryStateCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CountryStates and returns the data saved in the database.
   * @param {CountryStateCreateManyAndReturnArgs} args - Arguments to create many CountryStates.
   * @example
   * // Create many CountryStates
   * const countryState = await prisma.countryState.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CountryStates and only return the `id`
   * const countryStateWithIdOnly = await prisma.countryState.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CountryStateCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CountryStateCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CountryStatePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CountryState.
   * @param {CountryStateDeleteArgs} args - Arguments to delete one CountryState.
   * @example
   * // Delete one CountryState
   * const CountryState = await prisma.countryState.delete({
   *   where: {
   *     // ... filter to delete one CountryState
   *   }
   * })
   * 
   */
  delete<T extends CountryStateDeleteArgs>(args: Prisma.SelectSubset<T, CountryStateDeleteArgs<ExtArgs>>): Prisma.Prisma__CountryStateClient<runtime.Types.Result.GetResult<Prisma.$CountryStatePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CountryState.
   * @param {CountryStateUpdateArgs} args - Arguments to update one CountryState.
   * @example
   * // Update one CountryState
   * const countryState = await prisma.countryState.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CountryStateUpdateArgs>(args: Prisma.SelectSubset<T, CountryStateUpdateArgs<ExtArgs>>): Prisma.Prisma__CountryStateClient<runtime.Types.Result.GetResult<Prisma.$CountryStatePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CountryStates.
   * @param {CountryStateDeleteManyArgs} args - Arguments to filter CountryStates to delete.
   * @example
   * // Delete a few CountryStates
   * const { count } = await prisma.countryState.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CountryStateDeleteManyArgs>(args?: Prisma.SelectSubset<T, CountryStateDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CountryStates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryStateUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CountryStates
   * const countryState = await prisma.countryState.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CountryStateUpdateManyArgs>(args: Prisma.SelectSubset<T, CountryStateUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CountryStates and returns the data updated in the database.
   * @param {CountryStateUpdateManyAndReturnArgs} args - Arguments to update many CountryStates.
   * @example
   * // Update many CountryStates
   * const countryState = await prisma.countryState.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CountryStates and only return the `id`
   * const countryStateWithIdOnly = await prisma.countryState.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CountryStateUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CountryStateUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CountryStatePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CountryState.
   * @param {CountryStateUpsertArgs} args - Arguments to update or create a CountryState.
   * @example
   * // Update or create a CountryState
   * const countryState = await prisma.countryState.upsert({
   *   create: {
   *     // ... data to create a CountryState
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CountryState we want to update
   *   }
   * })
   */
  upsert<T extends CountryStateUpsertArgs>(args: Prisma.SelectSubset<T, CountryStateUpsertArgs<ExtArgs>>): Prisma.Prisma__CountryStateClient<runtime.Types.Result.GetResult<Prisma.$CountryStatePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CountryStates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryStateCountArgs} args - Arguments to filter CountryStates to count.
   * @example
   * // Count the number of CountryStates
   * const count = await prisma.countryState.count({
   *   where: {
   *     // ... the filter for the CountryStates we want to count
   *   }
   * })
  **/
  count<T extends CountryStateCountArgs>(
    args?: Prisma.Subset<T, CountryStateCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CountryStateCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CountryState.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryStateAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CountryStateAggregateArgs>(args: Prisma.Subset<T, CountryStateAggregateArgs>): Prisma.PrismaPromise<GetCountryStateAggregateType<T>>

  /**
   * Group by CountryState.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountryStateGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CountryStateGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CountryStateGroupByArgs['orderBy'] }
      : { orderBy?: CountryStateGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CountryStateGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCountryStateGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CountryState model
 */
readonly fields: CountryStateFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CountryState.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CountryStateClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  country<T extends Prisma.CountryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CountryDefaultArgs<ExtArgs>>): Prisma.Prisma__CountryClient<runtime.Types.Result.GetResult<Prisma.$CountryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.CountryState$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CountryState$usersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  stores<T extends Prisma.CountryState$storesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CountryState$storesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  warehouses<T extends Prisma.CountryState$warehousesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CountryState$warehousesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WarehousePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CountryState model
 */
export interface CountryStateFieldRefs {
  readonly id: Prisma.FieldRef<"CountryState", 'String'>
  readonly name: Prisma.FieldRef<"CountryState", 'String'>
  readonly countryId: Prisma.FieldRef<"CountryState", 'String'>
  readonly subdivisionCode: Prisma.FieldRef<"CountryState", 'String'>
  readonly tz: Prisma.FieldRef<"CountryState", 'String'>
  readonly flag: Prisma.FieldRef<"CountryState", 'String'>
  readonly createdAt: Prisma.FieldRef<"CountryState", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CountryState", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CountryState findUnique
 */
export type CountryStateFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryState
   */
  select?: Prisma.CountryStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryState
   */
  omit?: Prisma.CountryStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryStateInclude<ExtArgs> | null
  /**
   * Filter, which CountryState to fetch.
   */
  where: Prisma.CountryStateWhereUniqueInput
}

/**
 * CountryState findUniqueOrThrow
 */
export type CountryStateFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryState
   */
  select?: Prisma.CountryStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryState
   */
  omit?: Prisma.CountryStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryStateInclude<ExtArgs> | null
  /**
   * Filter, which CountryState to fetch.
   */
  where: Prisma.CountryStateWhereUniqueInput
}

/**
 * CountryState findFirst
 */
export type CountryStateFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryState
   */
  select?: Prisma.CountryStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryState
   */
  omit?: Prisma.CountryStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryStateInclude<ExtArgs> | null
  /**
   * Filter, which CountryState to fetch.
   */
  where?: Prisma.CountryStateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CountryStates to fetch.
   */
  orderBy?: Prisma.CountryStateOrderByWithRelationInput | Prisma.CountryStateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CountryStates.
   */
  cursor?: Prisma.CountryStateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CountryStates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CountryStates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CountryStates.
   */
  distinct?: Prisma.CountryStateScalarFieldEnum | Prisma.CountryStateScalarFieldEnum[]
}

/**
 * CountryState findFirstOrThrow
 */
export type CountryStateFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryState
   */
  select?: Prisma.CountryStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryState
   */
  omit?: Prisma.CountryStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryStateInclude<ExtArgs> | null
  /**
   * Filter, which CountryState to fetch.
   */
  where?: Prisma.CountryStateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CountryStates to fetch.
   */
  orderBy?: Prisma.CountryStateOrderByWithRelationInput | Prisma.CountryStateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CountryStates.
   */
  cursor?: Prisma.CountryStateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CountryStates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CountryStates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CountryStates.
   */
  distinct?: Prisma.CountryStateScalarFieldEnum | Prisma.CountryStateScalarFieldEnum[]
}

/**
 * CountryState findMany
 */
export type CountryStateFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryState
   */
  select?: Prisma.CountryStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryState
   */
  omit?: Prisma.CountryStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryStateInclude<ExtArgs> | null
  /**
   * Filter, which CountryStates to fetch.
   */
  where?: Prisma.CountryStateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CountryStates to fetch.
   */
  orderBy?: Prisma.CountryStateOrderByWithRelationInput | Prisma.CountryStateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CountryStates.
   */
  cursor?: Prisma.CountryStateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CountryStates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CountryStates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CountryStates.
   */
  distinct?: Prisma.CountryStateScalarFieldEnum | Prisma.CountryStateScalarFieldEnum[]
}

/**
 * CountryState create
 */
export type CountryStateCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryState
   */
  select?: Prisma.CountryStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryState
   */
  omit?: Prisma.CountryStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryStateInclude<ExtArgs> | null
  /**
   * The data needed to create a CountryState.
   */
  data: Prisma.XOR<Prisma.CountryStateCreateInput, Prisma.CountryStateUncheckedCreateInput>
}

/**
 * CountryState createMany
 */
export type CountryStateCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CountryStates.
   */
  data: Prisma.CountryStateCreateManyInput | Prisma.CountryStateCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CountryState createManyAndReturn
 */
export type CountryStateCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryState
   */
  select?: Prisma.CountryStateSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CountryState
   */
  omit?: Prisma.CountryStateOmit<ExtArgs> | null
  /**
   * The data used to create many CountryStates.
   */
  data: Prisma.CountryStateCreateManyInput | Prisma.CountryStateCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryStateIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CountryState update
 */
export type CountryStateUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryState
   */
  select?: Prisma.CountryStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryState
   */
  omit?: Prisma.CountryStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryStateInclude<ExtArgs> | null
  /**
   * The data needed to update a CountryState.
   */
  data: Prisma.XOR<Prisma.CountryStateUpdateInput, Prisma.CountryStateUncheckedUpdateInput>
  /**
   * Choose, which CountryState to update.
   */
  where: Prisma.CountryStateWhereUniqueInput
}

/**
 * CountryState updateMany
 */
export type CountryStateUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CountryStates.
   */
  data: Prisma.XOR<Prisma.CountryStateUpdateManyMutationInput, Prisma.CountryStateUncheckedUpdateManyInput>
  /**
   * Filter which CountryStates to update
   */
  where?: Prisma.CountryStateWhereInput
  /**
   * Limit how many CountryStates to update.
   */
  limit?: number
}

/**
 * CountryState updateManyAndReturn
 */
export type CountryStateUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryState
   */
  select?: Prisma.CountryStateSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CountryState
   */
  omit?: Prisma.CountryStateOmit<ExtArgs> | null
  /**
   * The data used to update CountryStates.
   */
  data: Prisma.XOR<Prisma.CountryStateUpdateManyMutationInput, Prisma.CountryStateUncheckedUpdateManyInput>
  /**
   * Filter which CountryStates to update
   */
  where?: Prisma.CountryStateWhereInput
  /**
   * Limit how many CountryStates to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryStateIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CountryState upsert
 */
export type CountryStateUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryState
   */
  select?: Prisma.CountryStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryState
   */
  omit?: Prisma.CountryStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryStateInclude<ExtArgs> | null
  /**
   * The filter to search for the CountryState to update in case it exists.
   */
  where: Prisma.CountryStateWhereUniqueInput
  /**
   * In case the CountryState found by the `where` argument doesn't exist, create a new CountryState with this data.
   */
  create: Prisma.XOR<Prisma.CountryStateCreateInput, Prisma.CountryStateUncheckedCreateInput>
  /**
   * In case the CountryState was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CountryStateUpdateInput, Prisma.CountryStateUncheckedUpdateInput>
}

/**
 * CountryState delete
 */
export type CountryStateDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryState
   */
  select?: Prisma.CountryStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryState
   */
  omit?: Prisma.CountryStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryStateInclude<ExtArgs> | null
  /**
   * Filter which CountryState to delete.
   */
  where: Prisma.CountryStateWhereUniqueInput
}

/**
 * CountryState deleteMany
 */
export type CountryStateDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CountryStates to delete
   */
  where?: Prisma.CountryStateWhereInput
  /**
   * Limit how many CountryStates to delete.
   */
  limit?: number
}

/**
 * CountryState.users
 */
export type CountryState$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  cursor?: Prisma.UserWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * CountryState.stores
 */
export type CountryState$storesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Store
   */
  select?: Prisma.StoreSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Store
   */
  omit?: Prisma.StoreOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreInclude<ExtArgs> | null
  where?: Prisma.StoreWhereInput
  orderBy?: Prisma.StoreOrderByWithRelationInput | Prisma.StoreOrderByWithRelationInput[]
  cursor?: Prisma.StoreWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StoreScalarFieldEnum | Prisma.StoreScalarFieldEnum[]
}

/**
 * CountryState.warehouses
 */
export type CountryState$warehousesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Warehouse
   */
  select?: Prisma.WarehouseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Warehouse
   */
  omit?: Prisma.WarehouseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WarehouseInclude<ExtArgs> | null
  where?: Prisma.WarehouseWhereInput
  orderBy?: Prisma.WarehouseOrderByWithRelationInput | Prisma.WarehouseOrderByWithRelationInput[]
  cursor?: Prisma.WarehouseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WarehouseScalarFieldEnum | Prisma.WarehouseScalarFieldEnum[]
}

/**
 * CountryState without action
 */
export type CountryStateDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CountryState
   */
  select?: Prisma.CountryStateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CountryState
   */
  omit?: Prisma.CountryStateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CountryStateInclude<ExtArgs> | null
}
