
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `McpOAuthCode` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model McpOAuthCode
 * 
 */
export type McpOAuthCodeModel = runtime.Types.Result.DefaultSelection<Prisma.$McpOAuthCodePayload>

export type AggregateMcpOAuthCode = {
  _count: McpOAuthCodeCountAggregateOutputType | null
  _min: McpOAuthCodeMinAggregateOutputType | null
  _max: McpOAuthCodeMaxAggregateOutputType | null
}

export type McpOAuthCodeMinAggregateOutputType = {
  id: string | null
  code: string | null
  clientId: string | null
  userId: string | null
  redirectUri: string | null
  codeChallenge: string | null
  codeChallengeMethod: string | null
  expiresAt: Date | null
  createdAt: Date | null
}

export type McpOAuthCodeMaxAggregateOutputType = {
  id: string | null
  code: string | null
  clientId: string | null
  userId: string | null
  redirectUri: string | null
  codeChallenge: string | null
  codeChallengeMethod: string | null
  expiresAt: Date | null
  createdAt: Date | null
}

export type McpOAuthCodeCountAggregateOutputType = {
  id: number
  code: number
  clientId: number
  userId: number
  redirectUri: number
  codeChallenge: number
  codeChallengeMethod: number
  expiresAt: number
  createdAt: number
  _all: number
}


export type McpOAuthCodeMinAggregateInputType = {
  id?: true
  code?: true
  clientId?: true
  userId?: true
  redirectUri?: true
  codeChallenge?: true
  codeChallengeMethod?: true
  expiresAt?: true
  createdAt?: true
}

export type McpOAuthCodeMaxAggregateInputType = {
  id?: true
  code?: true
  clientId?: true
  userId?: true
  redirectUri?: true
  codeChallenge?: true
  codeChallengeMethod?: true
  expiresAt?: true
  createdAt?: true
}

export type McpOAuthCodeCountAggregateInputType = {
  id?: true
  code?: true
  clientId?: true
  userId?: true
  redirectUri?: true
  codeChallenge?: true
  codeChallengeMethod?: true
  expiresAt?: true
  createdAt?: true
  _all?: true
}

export type McpOAuthCodeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which McpOAuthCode to aggregate.
   */
  where?: Prisma.McpOAuthCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McpOAuthCodes to fetch.
   */
  orderBy?: Prisma.McpOAuthCodeOrderByWithRelationInput | Prisma.McpOAuthCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.McpOAuthCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McpOAuthCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McpOAuthCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned McpOAuthCodes
  **/
  _count?: true | McpOAuthCodeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: McpOAuthCodeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: McpOAuthCodeMaxAggregateInputType
}

export type GetMcpOAuthCodeAggregateType<T extends McpOAuthCodeAggregateArgs> = {
      [P in keyof T & keyof AggregateMcpOAuthCode]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMcpOAuthCode[P]>
    : Prisma.GetScalarType<T[P], AggregateMcpOAuthCode[P]>
}




export type McpOAuthCodeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.McpOAuthCodeWhereInput
  orderBy?: Prisma.McpOAuthCodeOrderByWithAggregationInput | Prisma.McpOAuthCodeOrderByWithAggregationInput[]
  by: Prisma.McpOAuthCodeScalarFieldEnum[] | Prisma.McpOAuthCodeScalarFieldEnum
  having?: Prisma.McpOAuthCodeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: McpOAuthCodeCountAggregateInputType | true
  _min?: McpOAuthCodeMinAggregateInputType
  _max?: McpOAuthCodeMaxAggregateInputType
}

export type McpOAuthCodeGroupByOutputType = {
  id: string
  code: string
  clientId: string
  userId: string
  redirectUri: string
  codeChallenge: string
  codeChallengeMethod: string
  expiresAt: Date
  createdAt: Date
  _count: McpOAuthCodeCountAggregateOutputType | null
  _min: McpOAuthCodeMinAggregateOutputType | null
  _max: McpOAuthCodeMaxAggregateOutputType | null
}

export type GetMcpOAuthCodeGroupByPayload<T extends McpOAuthCodeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<McpOAuthCodeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof McpOAuthCodeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], McpOAuthCodeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], McpOAuthCodeGroupByOutputType[P]>
      }
    >
  >



export type McpOAuthCodeWhereInput = {
  AND?: Prisma.McpOAuthCodeWhereInput | Prisma.McpOAuthCodeWhereInput[]
  OR?: Prisma.McpOAuthCodeWhereInput[]
  NOT?: Prisma.McpOAuthCodeWhereInput | Prisma.McpOAuthCodeWhereInput[]
  id?: Prisma.UuidFilter<"McpOAuthCode"> | string
  code?: Prisma.StringFilter<"McpOAuthCode"> | string
  clientId?: Prisma.StringFilter<"McpOAuthCode"> | string
  userId?: Prisma.UuidFilter<"McpOAuthCode"> | string
  redirectUri?: Prisma.StringFilter<"McpOAuthCode"> | string
  codeChallenge?: Prisma.StringFilter<"McpOAuthCode"> | string
  codeChallengeMethod?: Prisma.StringFilter<"McpOAuthCode"> | string
  expiresAt?: Prisma.DateTimeFilter<"McpOAuthCode"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"McpOAuthCode"> | Date | string
}

export type McpOAuthCodeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  redirectUri?: Prisma.SortOrder
  codeChallenge?: Prisma.SortOrder
  codeChallengeMethod?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type McpOAuthCodeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  code?: string
  AND?: Prisma.McpOAuthCodeWhereInput | Prisma.McpOAuthCodeWhereInput[]
  OR?: Prisma.McpOAuthCodeWhereInput[]
  NOT?: Prisma.McpOAuthCodeWhereInput | Prisma.McpOAuthCodeWhereInput[]
  clientId?: Prisma.StringFilter<"McpOAuthCode"> | string
  userId?: Prisma.UuidFilter<"McpOAuthCode"> | string
  redirectUri?: Prisma.StringFilter<"McpOAuthCode"> | string
  codeChallenge?: Prisma.StringFilter<"McpOAuthCode"> | string
  codeChallengeMethod?: Prisma.StringFilter<"McpOAuthCode"> | string
  expiresAt?: Prisma.DateTimeFilter<"McpOAuthCode"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"McpOAuthCode"> | Date | string
}, "id" | "code">

export type McpOAuthCodeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  redirectUri?: Prisma.SortOrder
  codeChallenge?: Prisma.SortOrder
  codeChallengeMethod?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.McpOAuthCodeCountOrderByAggregateInput
  _max?: Prisma.McpOAuthCodeMaxOrderByAggregateInput
  _min?: Prisma.McpOAuthCodeMinOrderByAggregateInput
}

export type McpOAuthCodeScalarWhereWithAggregatesInput = {
  AND?: Prisma.McpOAuthCodeScalarWhereWithAggregatesInput | Prisma.McpOAuthCodeScalarWhereWithAggregatesInput[]
  OR?: Prisma.McpOAuthCodeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.McpOAuthCodeScalarWhereWithAggregatesInput | Prisma.McpOAuthCodeScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"McpOAuthCode"> | string
  code?: Prisma.StringWithAggregatesFilter<"McpOAuthCode"> | string
  clientId?: Prisma.StringWithAggregatesFilter<"McpOAuthCode"> | string
  userId?: Prisma.UuidWithAggregatesFilter<"McpOAuthCode"> | string
  redirectUri?: Prisma.StringWithAggregatesFilter<"McpOAuthCode"> | string
  codeChallenge?: Prisma.StringWithAggregatesFilter<"McpOAuthCode"> | string
  codeChallengeMethod?: Prisma.StringWithAggregatesFilter<"McpOAuthCode"> | string
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"McpOAuthCode"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"McpOAuthCode"> | Date | string
}

export type McpOAuthCodeCreateInput = {
  id?: string
  code: string
  clientId: string
  userId: string
  redirectUri: string
  codeChallenge: string
  codeChallengeMethod: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type McpOAuthCodeUncheckedCreateInput = {
  id?: string
  code: string
  clientId: string
  userId: string
  redirectUri: string
  codeChallenge: string
  codeChallengeMethod: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type McpOAuthCodeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  codeChallenge?: Prisma.StringFieldUpdateOperationsInput | string
  codeChallengeMethod?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type McpOAuthCodeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  codeChallenge?: Prisma.StringFieldUpdateOperationsInput | string
  codeChallengeMethod?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type McpOAuthCodeCreateManyInput = {
  id?: string
  code: string
  clientId: string
  userId: string
  redirectUri: string
  codeChallenge: string
  codeChallengeMethod: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type McpOAuthCodeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  codeChallenge?: Prisma.StringFieldUpdateOperationsInput | string
  codeChallengeMethod?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type McpOAuthCodeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  redirectUri?: Prisma.StringFieldUpdateOperationsInput | string
  codeChallenge?: Prisma.StringFieldUpdateOperationsInput | string
  codeChallengeMethod?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type McpOAuthCodeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  redirectUri?: Prisma.SortOrder
  codeChallenge?: Prisma.SortOrder
  codeChallengeMethod?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type McpOAuthCodeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  redirectUri?: Prisma.SortOrder
  codeChallenge?: Prisma.SortOrder
  codeChallengeMethod?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type McpOAuthCodeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  redirectUri?: Prisma.SortOrder
  codeChallenge?: Prisma.SortOrder
  codeChallengeMethod?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}



export type McpOAuthCodeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  clientId?: boolean
  userId?: boolean
  redirectUri?: boolean
  codeChallenge?: boolean
  codeChallengeMethod?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["mcpOAuthCode"]>

export type McpOAuthCodeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  clientId?: boolean
  userId?: boolean
  redirectUri?: boolean
  codeChallenge?: boolean
  codeChallengeMethod?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["mcpOAuthCode"]>

export type McpOAuthCodeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  clientId?: boolean
  userId?: boolean
  redirectUri?: boolean
  codeChallenge?: boolean
  codeChallengeMethod?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["mcpOAuthCode"]>

export type McpOAuthCodeSelectScalar = {
  id?: boolean
  code?: boolean
  clientId?: boolean
  userId?: boolean
  redirectUri?: boolean
  codeChallenge?: boolean
  codeChallengeMethod?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}

export type McpOAuthCodeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "code" | "clientId" | "userId" | "redirectUri" | "codeChallenge" | "codeChallengeMethod" | "expiresAt" | "createdAt", ExtArgs["result"]["mcpOAuthCode"]>

export type $McpOAuthCodePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "McpOAuthCode"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    code: string
    clientId: string
    userId: string
    redirectUri: string
    codeChallenge: string
    codeChallengeMethod: string
    expiresAt: Date
    createdAt: Date
  }, ExtArgs["result"]["mcpOAuthCode"]>
  composites: {}
}

export type McpOAuthCodeGetPayload<S extends boolean | null | undefined | McpOAuthCodeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$McpOAuthCodePayload, S>

export type McpOAuthCodeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<McpOAuthCodeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: McpOAuthCodeCountAggregateInputType | true
  }

export interface McpOAuthCodeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['McpOAuthCode'], meta: { name: 'McpOAuthCode' } }
  /**
   * Find zero or one McpOAuthCode that matches the filter.
   * @param {McpOAuthCodeFindUniqueArgs} args - Arguments to find a McpOAuthCode
   * @example
   * // Get one McpOAuthCode
   * const mcpOAuthCode = await prisma.mcpOAuthCode.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends McpOAuthCodeFindUniqueArgs>(args: Prisma.SelectSubset<T, McpOAuthCodeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__McpOAuthCodeClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthCodePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one McpOAuthCode that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {McpOAuthCodeFindUniqueOrThrowArgs} args - Arguments to find a McpOAuthCode
   * @example
   * // Get one McpOAuthCode
   * const mcpOAuthCode = await prisma.mcpOAuthCode.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends McpOAuthCodeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, McpOAuthCodeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__McpOAuthCodeClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthCodePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first McpOAuthCode that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthCodeFindFirstArgs} args - Arguments to find a McpOAuthCode
   * @example
   * // Get one McpOAuthCode
   * const mcpOAuthCode = await prisma.mcpOAuthCode.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends McpOAuthCodeFindFirstArgs>(args?: Prisma.SelectSubset<T, McpOAuthCodeFindFirstArgs<ExtArgs>>): Prisma.Prisma__McpOAuthCodeClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthCodePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first McpOAuthCode that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthCodeFindFirstOrThrowArgs} args - Arguments to find a McpOAuthCode
   * @example
   * // Get one McpOAuthCode
   * const mcpOAuthCode = await prisma.mcpOAuthCode.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends McpOAuthCodeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, McpOAuthCodeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__McpOAuthCodeClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthCodePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more McpOAuthCodes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthCodeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all McpOAuthCodes
   * const mcpOAuthCodes = await prisma.mcpOAuthCode.findMany()
   * 
   * // Get first 10 McpOAuthCodes
   * const mcpOAuthCodes = await prisma.mcpOAuthCode.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const mcpOAuthCodeWithIdOnly = await prisma.mcpOAuthCode.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends McpOAuthCodeFindManyArgs>(args?: Prisma.SelectSubset<T, McpOAuthCodeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McpOAuthCodePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a McpOAuthCode.
   * @param {McpOAuthCodeCreateArgs} args - Arguments to create a McpOAuthCode.
   * @example
   * // Create one McpOAuthCode
   * const McpOAuthCode = await prisma.mcpOAuthCode.create({
   *   data: {
   *     // ... data to create a McpOAuthCode
   *   }
   * })
   * 
   */
  create<T extends McpOAuthCodeCreateArgs>(args: Prisma.SelectSubset<T, McpOAuthCodeCreateArgs<ExtArgs>>): Prisma.Prisma__McpOAuthCodeClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthCodePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many McpOAuthCodes.
   * @param {McpOAuthCodeCreateManyArgs} args - Arguments to create many McpOAuthCodes.
   * @example
   * // Create many McpOAuthCodes
   * const mcpOAuthCode = await prisma.mcpOAuthCode.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends McpOAuthCodeCreateManyArgs>(args?: Prisma.SelectSubset<T, McpOAuthCodeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many McpOAuthCodes and returns the data saved in the database.
   * @param {McpOAuthCodeCreateManyAndReturnArgs} args - Arguments to create many McpOAuthCodes.
   * @example
   * // Create many McpOAuthCodes
   * const mcpOAuthCode = await prisma.mcpOAuthCode.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many McpOAuthCodes and only return the `id`
   * const mcpOAuthCodeWithIdOnly = await prisma.mcpOAuthCode.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends McpOAuthCodeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, McpOAuthCodeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McpOAuthCodePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a McpOAuthCode.
   * @param {McpOAuthCodeDeleteArgs} args - Arguments to delete one McpOAuthCode.
   * @example
   * // Delete one McpOAuthCode
   * const McpOAuthCode = await prisma.mcpOAuthCode.delete({
   *   where: {
   *     // ... filter to delete one McpOAuthCode
   *   }
   * })
   * 
   */
  delete<T extends McpOAuthCodeDeleteArgs>(args: Prisma.SelectSubset<T, McpOAuthCodeDeleteArgs<ExtArgs>>): Prisma.Prisma__McpOAuthCodeClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthCodePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one McpOAuthCode.
   * @param {McpOAuthCodeUpdateArgs} args - Arguments to update one McpOAuthCode.
   * @example
   * // Update one McpOAuthCode
   * const mcpOAuthCode = await prisma.mcpOAuthCode.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends McpOAuthCodeUpdateArgs>(args: Prisma.SelectSubset<T, McpOAuthCodeUpdateArgs<ExtArgs>>): Prisma.Prisma__McpOAuthCodeClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthCodePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more McpOAuthCodes.
   * @param {McpOAuthCodeDeleteManyArgs} args - Arguments to filter McpOAuthCodes to delete.
   * @example
   * // Delete a few McpOAuthCodes
   * const { count } = await prisma.mcpOAuthCode.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends McpOAuthCodeDeleteManyArgs>(args?: Prisma.SelectSubset<T, McpOAuthCodeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more McpOAuthCodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthCodeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many McpOAuthCodes
   * const mcpOAuthCode = await prisma.mcpOAuthCode.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends McpOAuthCodeUpdateManyArgs>(args: Prisma.SelectSubset<T, McpOAuthCodeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more McpOAuthCodes and returns the data updated in the database.
   * @param {McpOAuthCodeUpdateManyAndReturnArgs} args - Arguments to update many McpOAuthCodes.
   * @example
   * // Update many McpOAuthCodes
   * const mcpOAuthCode = await prisma.mcpOAuthCode.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more McpOAuthCodes and only return the `id`
   * const mcpOAuthCodeWithIdOnly = await prisma.mcpOAuthCode.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends McpOAuthCodeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, McpOAuthCodeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McpOAuthCodePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one McpOAuthCode.
   * @param {McpOAuthCodeUpsertArgs} args - Arguments to update or create a McpOAuthCode.
   * @example
   * // Update or create a McpOAuthCode
   * const mcpOAuthCode = await prisma.mcpOAuthCode.upsert({
   *   create: {
   *     // ... data to create a McpOAuthCode
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the McpOAuthCode we want to update
   *   }
   * })
   */
  upsert<T extends McpOAuthCodeUpsertArgs>(args: Prisma.SelectSubset<T, McpOAuthCodeUpsertArgs<ExtArgs>>): Prisma.Prisma__McpOAuthCodeClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthCodePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of McpOAuthCodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthCodeCountArgs} args - Arguments to filter McpOAuthCodes to count.
   * @example
   * // Count the number of McpOAuthCodes
   * const count = await prisma.mcpOAuthCode.count({
   *   where: {
   *     // ... the filter for the McpOAuthCodes we want to count
   *   }
   * })
  **/
  count<T extends McpOAuthCodeCountArgs>(
    args?: Prisma.Subset<T, McpOAuthCodeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], McpOAuthCodeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a McpOAuthCode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthCodeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends McpOAuthCodeAggregateArgs>(args: Prisma.Subset<T, McpOAuthCodeAggregateArgs>): Prisma.PrismaPromise<GetMcpOAuthCodeAggregateType<T>>

  /**
   * Group by McpOAuthCode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthCodeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends McpOAuthCodeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: McpOAuthCodeGroupByArgs['orderBy'] }
      : { orderBy?: McpOAuthCodeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, McpOAuthCodeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMcpOAuthCodeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the McpOAuthCode model
 */
readonly fields: McpOAuthCodeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for McpOAuthCode.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__McpOAuthCodeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the McpOAuthCode model
 */
export interface McpOAuthCodeFieldRefs {
  readonly id: Prisma.FieldRef<"McpOAuthCode", 'String'>
  readonly code: Prisma.FieldRef<"McpOAuthCode", 'String'>
  readonly clientId: Prisma.FieldRef<"McpOAuthCode", 'String'>
  readonly userId: Prisma.FieldRef<"McpOAuthCode", 'String'>
  readonly redirectUri: Prisma.FieldRef<"McpOAuthCode", 'String'>
  readonly codeChallenge: Prisma.FieldRef<"McpOAuthCode", 'String'>
  readonly codeChallengeMethod: Prisma.FieldRef<"McpOAuthCode", 'String'>
  readonly expiresAt: Prisma.FieldRef<"McpOAuthCode", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"McpOAuthCode", 'DateTime'>
}
    

// Custom InputTypes
/**
 * McpOAuthCode findUnique
 */
export type McpOAuthCodeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthCode
   */
  select?: Prisma.McpOAuthCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthCode
   */
  omit?: Prisma.McpOAuthCodeOmit<ExtArgs> | null
  /**
   * Filter, which McpOAuthCode to fetch.
   */
  where: Prisma.McpOAuthCodeWhereUniqueInput
}

/**
 * McpOAuthCode findUniqueOrThrow
 */
export type McpOAuthCodeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthCode
   */
  select?: Prisma.McpOAuthCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthCode
   */
  omit?: Prisma.McpOAuthCodeOmit<ExtArgs> | null
  /**
   * Filter, which McpOAuthCode to fetch.
   */
  where: Prisma.McpOAuthCodeWhereUniqueInput
}

/**
 * McpOAuthCode findFirst
 */
export type McpOAuthCodeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthCode
   */
  select?: Prisma.McpOAuthCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthCode
   */
  omit?: Prisma.McpOAuthCodeOmit<ExtArgs> | null
  /**
   * Filter, which McpOAuthCode to fetch.
   */
  where?: Prisma.McpOAuthCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McpOAuthCodes to fetch.
   */
  orderBy?: Prisma.McpOAuthCodeOrderByWithRelationInput | Prisma.McpOAuthCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for McpOAuthCodes.
   */
  cursor?: Prisma.McpOAuthCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McpOAuthCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McpOAuthCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of McpOAuthCodes.
   */
  distinct?: Prisma.McpOAuthCodeScalarFieldEnum | Prisma.McpOAuthCodeScalarFieldEnum[]
}

/**
 * McpOAuthCode findFirstOrThrow
 */
export type McpOAuthCodeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthCode
   */
  select?: Prisma.McpOAuthCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthCode
   */
  omit?: Prisma.McpOAuthCodeOmit<ExtArgs> | null
  /**
   * Filter, which McpOAuthCode to fetch.
   */
  where?: Prisma.McpOAuthCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McpOAuthCodes to fetch.
   */
  orderBy?: Prisma.McpOAuthCodeOrderByWithRelationInput | Prisma.McpOAuthCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for McpOAuthCodes.
   */
  cursor?: Prisma.McpOAuthCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McpOAuthCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McpOAuthCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of McpOAuthCodes.
   */
  distinct?: Prisma.McpOAuthCodeScalarFieldEnum | Prisma.McpOAuthCodeScalarFieldEnum[]
}

/**
 * McpOAuthCode findMany
 */
export type McpOAuthCodeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthCode
   */
  select?: Prisma.McpOAuthCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthCode
   */
  omit?: Prisma.McpOAuthCodeOmit<ExtArgs> | null
  /**
   * Filter, which McpOAuthCodes to fetch.
   */
  where?: Prisma.McpOAuthCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McpOAuthCodes to fetch.
   */
  orderBy?: Prisma.McpOAuthCodeOrderByWithRelationInput | Prisma.McpOAuthCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing McpOAuthCodes.
   */
  cursor?: Prisma.McpOAuthCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McpOAuthCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McpOAuthCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of McpOAuthCodes.
   */
  distinct?: Prisma.McpOAuthCodeScalarFieldEnum | Prisma.McpOAuthCodeScalarFieldEnum[]
}

/**
 * McpOAuthCode create
 */
export type McpOAuthCodeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthCode
   */
  select?: Prisma.McpOAuthCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthCode
   */
  omit?: Prisma.McpOAuthCodeOmit<ExtArgs> | null
  /**
   * The data needed to create a McpOAuthCode.
   */
  data: Prisma.XOR<Prisma.McpOAuthCodeCreateInput, Prisma.McpOAuthCodeUncheckedCreateInput>
}

/**
 * McpOAuthCode createMany
 */
export type McpOAuthCodeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many McpOAuthCodes.
   */
  data: Prisma.McpOAuthCodeCreateManyInput | Prisma.McpOAuthCodeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * McpOAuthCode createManyAndReturn
 */
export type McpOAuthCodeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthCode
   */
  select?: Prisma.McpOAuthCodeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthCode
   */
  omit?: Prisma.McpOAuthCodeOmit<ExtArgs> | null
  /**
   * The data used to create many McpOAuthCodes.
   */
  data: Prisma.McpOAuthCodeCreateManyInput | Prisma.McpOAuthCodeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * McpOAuthCode update
 */
export type McpOAuthCodeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthCode
   */
  select?: Prisma.McpOAuthCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthCode
   */
  omit?: Prisma.McpOAuthCodeOmit<ExtArgs> | null
  /**
   * The data needed to update a McpOAuthCode.
   */
  data: Prisma.XOR<Prisma.McpOAuthCodeUpdateInput, Prisma.McpOAuthCodeUncheckedUpdateInput>
  /**
   * Choose, which McpOAuthCode to update.
   */
  where: Prisma.McpOAuthCodeWhereUniqueInput
}

/**
 * McpOAuthCode updateMany
 */
export type McpOAuthCodeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update McpOAuthCodes.
   */
  data: Prisma.XOR<Prisma.McpOAuthCodeUpdateManyMutationInput, Prisma.McpOAuthCodeUncheckedUpdateManyInput>
  /**
   * Filter which McpOAuthCodes to update
   */
  where?: Prisma.McpOAuthCodeWhereInput
  /**
   * Limit how many McpOAuthCodes to update.
   */
  limit?: number
}

/**
 * McpOAuthCode updateManyAndReturn
 */
export type McpOAuthCodeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthCode
   */
  select?: Prisma.McpOAuthCodeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthCode
   */
  omit?: Prisma.McpOAuthCodeOmit<ExtArgs> | null
  /**
   * The data used to update McpOAuthCodes.
   */
  data: Prisma.XOR<Prisma.McpOAuthCodeUpdateManyMutationInput, Prisma.McpOAuthCodeUncheckedUpdateManyInput>
  /**
   * Filter which McpOAuthCodes to update
   */
  where?: Prisma.McpOAuthCodeWhereInput
  /**
   * Limit how many McpOAuthCodes to update.
   */
  limit?: number
}

/**
 * McpOAuthCode upsert
 */
export type McpOAuthCodeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthCode
   */
  select?: Prisma.McpOAuthCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthCode
   */
  omit?: Prisma.McpOAuthCodeOmit<ExtArgs> | null
  /**
   * The filter to search for the McpOAuthCode to update in case it exists.
   */
  where: Prisma.McpOAuthCodeWhereUniqueInput
  /**
   * In case the McpOAuthCode found by the `where` argument doesn't exist, create a new McpOAuthCode with this data.
   */
  create: Prisma.XOR<Prisma.McpOAuthCodeCreateInput, Prisma.McpOAuthCodeUncheckedCreateInput>
  /**
   * In case the McpOAuthCode was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.McpOAuthCodeUpdateInput, Prisma.McpOAuthCodeUncheckedUpdateInput>
}

/**
 * McpOAuthCode delete
 */
export type McpOAuthCodeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthCode
   */
  select?: Prisma.McpOAuthCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthCode
   */
  omit?: Prisma.McpOAuthCodeOmit<ExtArgs> | null
  /**
   * Filter which McpOAuthCode to delete.
   */
  where: Prisma.McpOAuthCodeWhereUniqueInput
}

/**
 * McpOAuthCode deleteMany
 */
export type McpOAuthCodeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which McpOAuthCodes to delete
   */
  where?: Prisma.McpOAuthCodeWhereInput
  /**
   * Limit how many McpOAuthCodes to delete.
   */
  limit?: number
}

/**
 * McpOAuthCode without action
 */
export type McpOAuthCodeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthCode
   */
  select?: Prisma.McpOAuthCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthCode
   */
  omit?: Prisma.McpOAuthCodeOmit<ExtArgs> | null
}
