
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `McpOAuthClient` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model McpOAuthClient
 * 
 */
export type McpOAuthClientModel = runtime.Types.Result.DefaultSelection<Prisma.$McpOAuthClientPayload>

export type AggregateMcpOAuthClient = {
  _count: McpOAuthClientCountAggregateOutputType | null
  _min: McpOAuthClientMinAggregateOutputType | null
  _max: McpOAuthClientMaxAggregateOutputType | null
}

export type McpOAuthClientMinAggregateOutputType = {
  id: string | null
  clientId: string | null
  clientName: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type McpOAuthClientMaxAggregateOutputType = {
  id: string | null
  clientId: string | null
  clientName: string | null
  userId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type McpOAuthClientCountAggregateOutputType = {
  id: number
  clientId: number
  clientName: number
  redirectUris: number
  userId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type McpOAuthClientMinAggregateInputType = {
  id?: true
  clientId?: true
  clientName?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type McpOAuthClientMaxAggregateInputType = {
  id?: true
  clientId?: true
  clientName?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
}

export type McpOAuthClientCountAggregateInputType = {
  id?: true
  clientId?: true
  clientName?: true
  redirectUris?: true
  userId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type McpOAuthClientAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which McpOAuthClient to aggregate.
   */
  where?: Prisma.McpOAuthClientWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McpOAuthClients to fetch.
   */
  orderBy?: Prisma.McpOAuthClientOrderByWithRelationInput | Prisma.McpOAuthClientOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.McpOAuthClientWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McpOAuthClients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McpOAuthClients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned McpOAuthClients
  **/
  _count?: true | McpOAuthClientCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: McpOAuthClientMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: McpOAuthClientMaxAggregateInputType
}

export type GetMcpOAuthClientAggregateType<T extends McpOAuthClientAggregateArgs> = {
      [P in keyof T & keyof AggregateMcpOAuthClient]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMcpOAuthClient[P]>
    : Prisma.GetScalarType<T[P], AggregateMcpOAuthClient[P]>
}




export type McpOAuthClientGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.McpOAuthClientWhereInput
  orderBy?: Prisma.McpOAuthClientOrderByWithAggregationInput | Prisma.McpOAuthClientOrderByWithAggregationInput[]
  by: Prisma.McpOAuthClientScalarFieldEnum[] | Prisma.McpOAuthClientScalarFieldEnum
  having?: Prisma.McpOAuthClientScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: McpOAuthClientCountAggregateInputType | true
  _min?: McpOAuthClientMinAggregateInputType
  _max?: McpOAuthClientMaxAggregateInputType
}

export type McpOAuthClientGroupByOutputType = {
  id: string
  clientId: string
  clientName: string
  redirectUris: string[]
  userId: string | null
  createdAt: Date
  updatedAt: Date
  _count: McpOAuthClientCountAggregateOutputType | null
  _min: McpOAuthClientMinAggregateOutputType | null
  _max: McpOAuthClientMaxAggregateOutputType | null
}

export type GetMcpOAuthClientGroupByPayload<T extends McpOAuthClientGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<McpOAuthClientGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof McpOAuthClientGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], McpOAuthClientGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], McpOAuthClientGroupByOutputType[P]>
      }
    >
  >



export type McpOAuthClientWhereInput = {
  AND?: Prisma.McpOAuthClientWhereInput | Prisma.McpOAuthClientWhereInput[]
  OR?: Prisma.McpOAuthClientWhereInput[]
  NOT?: Prisma.McpOAuthClientWhereInput | Prisma.McpOAuthClientWhereInput[]
  id?: Prisma.UuidFilter<"McpOAuthClient"> | string
  clientId?: Prisma.StringFilter<"McpOAuthClient"> | string
  clientName?: Prisma.StringFilter<"McpOAuthClient"> | string
  redirectUris?: Prisma.StringNullableListFilter<"McpOAuthClient">
  userId?: Prisma.UuidNullableFilter<"McpOAuthClient"> | string | null
  createdAt?: Prisma.DateTimeFilter<"McpOAuthClient"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"McpOAuthClient"> | Date | string
}

export type McpOAuthClientOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  clientName?: Prisma.SortOrder
  redirectUris?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type McpOAuthClientWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  clientId?: string
  AND?: Prisma.McpOAuthClientWhereInput | Prisma.McpOAuthClientWhereInput[]
  OR?: Prisma.McpOAuthClientWhereInput[]
  NOT?: Prisma.McpOAuthClientWhereInput | Prisma.McpOAuthClientWhereInput[]
  clientName?: Prisma.StringFilter<"McpOAuthClient"> | string
  redirectUris?: Prisma.StringNullableListFilter<"McpOAuthClient">
  userId?: Prisma.UuidNullableFilter<"McpOAuthClient"> | string | null
  createdAt?: Prisma.DateTimeFilter<"McpOAuthClient"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"McpOAuthClient"> | Date | string
}, "id" | "clientId">

export type McpOAuthClientOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  clientName?: Prisma.SortOrder
  redirectUris?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.McpOAuthClientCountOrderByAggregateInput
  _max?: Prisma.McpOAuthClientMaxOrderByAggregateInput
  _min?: Prisma.McpOAuthClientMinOrderByAggregateInput
}

export type McpOAuthClientScalarWhereWithAggregatesInput = {
  AND?: Prisma.McpOAuthClientScalarWhereWithAggregatesInput | Prisma.McpOAuthClientScalarWhereWithAggregatesInput[]
  OR?: Prisma.McpOAuthClientScalarWhereWithAggregatesInput[]
  NOT?: Prisma.McpOAuthClientScalarWhereWithAggregatesInput | Prisma.McpOAuthClientScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"McpOAuthClient"> | string
  clientId?: Prisma.StringWithAggregatesFilter<"McpOAuthClient"> | string
  clientName?: Prisma.StringWithAggregatesFilter<"McpOAuthClient"> | string
  redirectUris?: Prisma.StringNullableListFilter<"McpOAuthClient">
  userId?: Prisma.UuidNullableWithAggregatesFilter<"McpOAuthClient"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"McpOAuthClient"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"McpOAuthClient"> | Date | string
}

export type McpOAuthClientCreateInput = {
  id?: string
  clientId: string
  clientName: string
  redirectUris?: Prisma.McpOAuthClientCreateredirectUrisInput | string[]
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type McpOAuthClientUncheckedCreateInput = {
  id?: string
  clientId: string
  clientName: string
  redirectUris?: Prisma.McpOAuthClientCreateredirectUrisInput | string[]
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type McpOAuthClientUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  clientName?: Prisma.StringFieldUpdateOperationsInput | string
  redirectUris?: Prisma.McpOAuthClientUpdateredirectUrisInput | string[]
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type McpOAuthClientUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  clientName?: Prisma.StringFieldUpdateOperationsInput | string
  redirectUris?: Prisma.McpOAuthClientUpdateredirectUrisInput | string[]
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type McpOAuthClientCreateManyInput = {
  id?: string
  clientId: string
  clientName: string
  redirectUris?: Prisma.McpOAuthClientCreateredirectUrisInput | string[]
  userId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type McpOAuthClientUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  clientName?: Prisma.StringFieldUpdateOperationsInput | string
  redirectUris?: Prisma.McpOAuthClientUpdateredirectUrisInput | string[]
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type McpOAuthClientUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.StringFieldUpdateOperationsInput | string
  clientName?: Prisma.StringFieldUpdateOperationsInput | string
  redirectUris?: Prisma.McpOAuthClientUpdateredirectUrisInput | string[]
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type McpOAuthClientCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  clientName?: Prisma.SortOrder
  redirectUris?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type McpOAuthClientMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  clientName?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type McpOAuthClientMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  clientName?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type McpOAuthClientCreateredirectUrisInput = {
  set: string[]
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type McpOAuthClientUpdateredirectUrisInput = {
  set?: string[]
  push?: string | string[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type McpOAuthClientSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clientId?: boolean
  clientName?: boolean
  redirectUris?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["mcpOAuthClient"]>

export type McpOAuthClientSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clientId?: boolean
  clientName?: boolean
  redirectUris?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["mcpOAuthClient"]>

export type McpOAuthClientSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  clientId?: boolean
  clientName?: boolean
  redirectUris?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["mcpOAuthClient"]>

export type McpOAuthClientSelectScalar = {
  id?: boolean
  clientId?: boolean
  clientName?: boolean
  redirectUris?: boolean
  userId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type McpOAuthClientOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "clientId" | "clientName" | "redirectUris" | "userId" | "createdAt" | "updatedAt", ExtArgs["result"]["mcpOAuthClient"]>

export type $McpOAuthClientPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "McpOAuthClient"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    clientId: string
    clientName: string
    redirectUris: string[]
    userId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["mcpOAuthClient"]>
  composites: {}
}

export type McpOAuthClientGetPayload<S extends boolean | null | undefined | McpOAuthClientDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$McpOAuthClientPayload, S>

export type McpOAuthClientCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<McpOAuthClientFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: McpOAuthClientCountAggregateInputType | true
  }

export interface McpOAuthClientDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['McpOAuthClient'], meta: { name: 'McpOAuthClient' } }
  /**
   * Find zero or one McpOAuthClient that matches the filter.
   * @param {McpOAuthClientFindUniqueArgs} args - Arguments to find a McpOAuthClient
   * @example
   * // Get one McpOAuthClient
   * const mcpOAuthClient = await prisma.mcpOAuthClient.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends McpOAuthClientFindUniqueArgs>(args: Prisma.SelectSubset<T, McpOAuthClientFindUniqueArgs<ExtArgs>>): Prisma.Prisma__McpOAuthClientClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthClientPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one McpOAuthClient that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {McpOAuthClientFindUniqueOrThrowArgs} args - Arguments to find a McpOAuthClient
   * @example
   * // Get one McpOAuthClient
   * const mcpOAuthClient = await prisma.mcpOAuthClient.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends McpOAuthClientFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, McpOAuthClientFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__McpOAuthClientClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthClientPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first McpOAuthClient that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthClientFindFirstArgs} args - Arguments to find a McpOAuthClient
   * @example
   * // Get one McpOAuthClient
   * const mcpOAuthClient = await prisma.mcpOAuthClient.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends McpOAuthClientFindFirstArgs>(args?: Prisma.SelectSubset<T, McpOAuthClientFindFirstArgs<ExtArgs>>): Prisma.Prisma__McpOAuthClientClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthClientPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first McpOAuthClient that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthClientFindFirstOrThrowArgs} args - Arguments to find a McpOAuthClient
   * @example
   * // Get one McpOAuthClient
   * const mcpOAuthClient = await prisma.mcpOAuthClient.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends McpOAuthClientFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, McpOAuthClientFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__McpOAuthClientClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthClientPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more McpOAuthClients that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthClientFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all McpOAuthClients
   * const mcpOAuthClients = await prisma.mcpOAuthClient.findMany()
   * 
   * // Get first 10 McpOAuthClients
   * const mcpOAuthClients = await prisma.mcpOAuthClient.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const mcpOAuthClientWithIdOnly = await prisma.mcpOAuthClient.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends McpOAuthClientFindManyArgs>(args?: Prisma.SelectSubset<T, McpOAuthClientFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McpOAuthClientPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a McpOAuthClient.
   * @param {McpOAuthClientCreateArgs} args - Arguments to create a McpOAuthClient.
   * @example
   * // Create one McpOAuthClient
   * const McpOAuthClient = await prisma.mcpOAuthClient.create({
   *   data: {
   *     // ... data to create a McpOAuthClient
   *   }
   * })
   * 
   */
  create<T extends McpOAuthClientCreateArgs>(args: Prisma.SelectSubset<T, McpOAuthClientCreateArgs<ExtArgs>>): Prisma.Prisma__McpOAuthClientClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthClientPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many McpOAuthClients.
   * @param {McpOAuthClientCreateManyArgs} args - Arguments to create many McpOAuthClients.
   * @example
   * // Create many McpOAuthClients
   * const mcpOAuthClient = await prisma.mcpOAuthClient.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends McpOAuthClientCreateManyArgs>(args?: Prisma.SelectSubset<T, McpOAuthClientCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many McpOAuthClients and returns the data saved in the database.
   * @param {McpOAuthClientCreateManyAndReturnArgs} args - Arguments to create many McpOAuthClients.
   * @example
   * // Create many McpOAuthClients
   * const mcpOAuthClient = await prisma.mcpOAuthClient.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many McpOAuthClients and only return the `id`
   * const mcpOAuthClientWithIdOnly = await prisma.mcpOAuthClient.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends McpOAuthClientCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, McpOAuthClientCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McpOAuthClientPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a McpOAuthClient.
   * @param {McpOAuthClientDeleteArgs} args - Arguments to delete one McpOAuthClient.
   * @example
   * // Delete one McpOAuthClient
   * const McpOAuthClient = await prisma.mcpOAuthClient.delete({
   *   where: {
   *     // ... filter to delete one McpOAuthClient
   *   }
   * })
   * 
   */
  delete<T extends McpOAuthClientDeleteArgs>(args: Prisma.SelectSubset<T, McpOAuthClientDeleteArgs<ExtArgs>>): Prisma.Prisma__McpOAuthClientClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthClientPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one McpOAuthClient.
   * @param {McpOAuthClientUpdateArgs} args - Arguments to update one McpOAuthClient.
   * @example
   * // Update one McpOAuthClient
   * const mcpOAuthClient = await prisma.mcpOAuthClient.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends McpOAuthClientUpdateArgs>(args: Prisma.SelectSubset<T, McpOAuthClientUpdateArgs<ExtArgs>>): Prisma.Prisma__McpOAuthClientClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthClientPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more McpOAuthClients.
   * @param {McpOAuthClientDeleteManyArgs} args - Arguments to filter McpOAuthClients to delete.
   * @example
   * // Delete a few McpOAuthClients
   * const { count } = await prisma.mcpOAuthClient.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends McpOAuthClientDeleteManyArgs>(args?: Prisma.SelectSubset<T, McpOAuthClientDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more McpOAuthClients.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthClientUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many McpOAuthClients
   * const mcpOAuthClient = await prisma.mcpOAuthClient.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends McpOAuthClientUpdateManyArgs>(args: Prisma.SelectSubset<T, McpOAuthClientUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more McpOAuthClients and returns the data updated in the database.
   * @param {McpOAuthClientUpdateManyAndReturnArgs} args - Arguments to update many McpOAuthClients.
   * @example
   * // Update many McpOAuthClients
   * const mcpOAuthClient = await prisma.mcpOAuthClient.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more McpOAuthClients and only return the `id`
   * const mcpOAuthClientWithIdOnly = await prisma.mcpOAuthClient.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends McpOAuthClientUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, McpOAuthClientUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McpOAuthClientPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one McpOAuthClient.
   * @param {McpOAuthClientUpsertArgs} args - Arguments to update or create a McpOAuthClient.
   * @example
   * // Update or create a McpOAuthClient
   * const mcpOAuthClient = await prisma.mcpOAuthClient.upsert({
   *   create: {
   *     // ... data to create a McpOAuthClient
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the McpOAuthClient we want to update
   *   }
   * })
   */
  upsert<T extends McpOAuthClientUpsertArgs>(args: Prisma.SelectSubset<T, McpOAuthClientUpsertArgs<ExtArgs>>): Prisma.Prisma__McpOAuthClientClient<runtime.Types.Result.GetResult<Prisma.$McpOAuthClientPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of McpOAuthClients.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthClientCountArgs} args - Arguments to filter McpOAuthClients to count.
   * @example
   * // Count the number of McpOAuthClients
   * const count = await prisma.mcpOAuthClient.count({
   *   where: {
   *     // ... the filter for the McpOAuthClients we want to count
   *   }
   * })
  **/
  count<T extends McpOAuthClientCountArgs>(
    args?: Prisma.Subset<T, McpOAuthClientCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], McpOAuthClientCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a McpOAuthClient.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthClientAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends McpOAuthClientAggregateArgs>(args: Prisma.Subset<T, McpOAuthClientAggregateArgs>): Prisma.PrismaPromise<GetMcpOAuthClientAggregateType<T>>

  /**
   * Group by McpOAuthClient.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpOAuthClientGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends McpOAuthClientGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: McpOAuthClientGroupByArgs['orderBy'] }
      : { orderBy?: McpOAuthClientGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, McpOAuthClientGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMcpOAuthClientGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the McpOAuthClient model
 */
readonly fields: McpOAuthClientFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for McpOAuthClient.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__McpOAuthClientClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the McpOAuthClient model
 */
export interface McpOAuthClientFieldRefs {
  readonly id: Prisma.FieldRef<"McpOAuthClient", 'String'>
  readonly clientId: Prisma.FieldRef<"McpOAuthClient", 'String'>
  readonly clientName: Prisma.FieldRef<"McpOAuthClient", 'String'>
  readonly redirectUris: Prisma.FieldRef<"McpOAuthClient", 'String[]'>
  readonly userId: Prisma.FieldRef<"McpOAuthClient", 'String'>
  readonly createdAt: Prisma.FieldRef<"McpOAuthClient", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"McpOAuthClient", 'DateTime'>
}
    

// Custom InputTypes
/**
 * McpOAuthClient findUnique
 */
export type McpOAuthClientFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthClient
   */
  select?: Prisma.McpOAuthClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthClient
   */
  omit?: Prisma.McpOAuthClientOmit<ExtArgs> | null
  /**
   * Filter, which McpOAuthClient to fetch.
   */
  where: Prisma.McpOAuthClientWhereUniqueInput
}

/**
 * McpOAuthClient findUniqueOrThrow
 */
export type McpOAuthClientFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthClient
   */
  select?: Prisma.McpOAuthClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthClient
   */
  omit?: Prisma.McpOAuthClientOmit<ExtArgs> | null
  /**
   * Filter, which McpOAuthClient to fetch.
   */
  where: Prisma.McpOAuthClientWhereUniqueInput
}

/**
 * McpOAuthClient findFirst
 */
export type McpOAuthClientFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthClient
   */
  select?: Prisma.McpOAuthClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthClient
   */
  omit?: Prisma.McpOAuthClientOmit<ExtArgs> | null
  /**
   * Filter, which McpOAuthClient to fetch.
   */
  where?: Prisma.McpOAuthClientWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McpOAuthClients to fetch.
   */
  orderBy?: Prisma.McpOAuthClientOrderByWithRelationInput | Prisma.McpOAuthClientOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for McpOAuthClients.
   */
  cursor?: Prisma.McpOAuthClientWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McpOAuthClients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McpOAuthClients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of McpOAuthClients.
   */
  distinct?: Prisma.McpOAuthClientScalarFieldEnum | Prisma.McpOAuthClientScalarFieldEnum[]
}

/**
 * McpOAuthClient findFirstOrThrow
 */
export type McpOAuthClientFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthClient
   */
  select?: Prisma.McpOAuthClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthClient
   */
  omit?: Prisma.McpOAuthClientOmit<ExtArgs> | null
  /**
   * Filter, which McpOAuthClient to fetch.
   */
  where?: Prisma.McpOAuthClientWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McpOAuthClients to fetch.
   */
  orderBy?: Prisma.McpOAuthClientOrderByWithRelationInput | Prisma.McpOAuthClientOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for McpOAuthClients.
   */
  cursor?: Prisma.McpOAuthClientWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McpOAuthClients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McpOAuthClients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of McpOAuthClients.
   */
  distinct?: Prisma.McpOAuthClientScalarFieldEnum | Prisma.McpOAuthClientScalarFieldEnum[]
}

/**
 * McpOAuthClient findMany
 */
export type McpOAuthClientFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthClient
   */
  select?: Prisma.McpOAuthClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthClient
   */
  omit?: Prisma.McpOAuthClientOmit<ExtArgs> | null
  /**
   * Filter, which McpOAuthClients to fetch.
   */
  where?: Prisma.McpOAuthClientWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McpOAuthClients to fetch.
   */
  orderBy?: Prisma.McpOAuthClientOrderByWithRelationInput | Prisma.McpOAuthClientOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing McpOAuthClients.
   */
  cursor?: Prisma.McpOAuthClientWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McpOAuthClients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McpOAuthClients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of McpOAuthClients.
   */
  distinct?: Prisma.McpOAuthClientScalarFieldEnum | Prisma.McpOAuthClientScalarFieldEnum[]
}

/**
 * McpOAuthClient create
 */
export type McpOAuthClientCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthClient
   */
  select?: Prisma.McpOAuthClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthClient
   */
  omit?: Prisma.McpOAuthClientOmit<ExtArgs> | null
  /**
   * The data needed to create a McpOAuthClient.
   */
  data: Prisma.XOR<Prisma.McpOAuthClientCreateInput, Prisma.McpOAuthClientUncheckedCreateInput>
}

/**
 * McpOAuthClient createMany
 */
export type McpOAuthClientCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many McpOAuthClients.
   */
  data: Prisma.McpOAuthClientCreateManyInput | Prisma.McpOAuthClientCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * McpOAuthClient createManyAndReturn
 */
export type McpOAuthClientCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthClient
   */
  select?: Prisma.McpOAuthClientSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthClient
   */
  omit?: Prisma.McpOAuthClientOmit<ExtArgs> | null
  /**
   * The data used to create many McpOAuthClients.
   */
  data: Prisma.McpOAuthClientCreateManyInput | Prisma.McpOAuthClientCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * McpOAuthClient update
 */
export type McpOAuthClientUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthClient
   */
  select?: Prisma.McpOAuthClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthClient
   */
  omit?: Prisma.McpOAuthClientOmit<ExtArgs> | null
  /**
   * The data needed to update a McpOAuthClient.
   */
  data: Prisma.XOR<Prisma.McpOAuthClientUpdateInput, Prisma.McpOAuthClientUncheckedUpdateInput>
  /**
   * Choose, which McpOAuthClient to update.
   */
  where: Prisma.McpOAuthClientWhereUniqueInput
}

/**
 * McpOAuthClient updateMany
 */
export type McpOAuthClientUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update McpOAuthClients.
   */
  data: Prisma.XOR<Prisma.McpOAuthClientUpdateManyMutationInput, Prisma.McpOAuthClientUncheckedUpdateManyInput>
  /**
   * Filter which McpOAuthClients to update
   */
  where?: Prisma.McpOAuthClientWhereInput
  /**
   * Limit how many McpOAuthClients to update.
   */
  limit?: number
}

/**
 * McpOAuthClient updateManyAndReturn
 */
export type McpOAuthClientUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthClient
   */
  select?: Prisma.McpOAuthClientSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthClient
   */
  omit?: Prisma.McpOAuthClientOmit<ExtArgs> | null
  /**
   * The data used to update McpOAuthClients.
   */
  data: Prisma.XOR<Prisma.McpOAuthClientUpdateManyMutationInput, Prisma.McpOAuthClientUncheckedUpdateManyInput>
  /**
   * Filter which McpOAuthClients to update
   */
  where?: Prisma.McpOAuthClientWhereInput
  /**
   * Limit how many McpOAuthClients to update.
   */
  limit?: number
}

/**
 * McpOAuthClient upsert
 */
export type McpOAuthClientUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthClient
   */
  select?: Prisma.McpOAuthClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthClient
   */
  omit?: Prisma.McpOAuthClientOmit<ExtArgs> | null
  /**
   * The filter to search for the McpOAuthClient to update in case it exists.
   */
  where: Prisma.McpOAuthClientWhereUniqueInput
  /**
   * In case the McpOAuthClient found by the `where` argument doesn't exist, create a new McpOAuthClient with this data.
   */
  create: Prisma.XOR<Prisma.McpOAuthClientCreateInput, Prisma.McpOAuthClientUncheckedCreateInput>
  /**
   * In case the McpOAuthClient was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.McpOAuthClientUpdateInput, Prisma.McpOAuthClientUncheckedUpdateInput>
}

/**
 * McpOAuthClient delete
 */
export type McpOAuthClientDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthClient
   */
  select?: Prisma.McpOAuthClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthClient
   */
  omit?: Prisma.McpOAuthClientOmit<ExtArgs> | null
  /**
   * Filter which McpOAuthClient to delete.
   */
  where: Prisma.McpOAuthClientWhereUniqueInput
}

/**
 * McpOAuthClient deleteMany
 */
export type McpOAuthClientDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which McpOAuthClients to delete
   */
  where?: Prisma.McpOAuthClientWhereInput
  /**
   * Limit how many McpOAuthClients to delete.
   */
  limit?: number
}

/**
 * McpOAuthClient without action
 */
export type McpOAuthClientDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpOAuthClient
   */
  select?: Prisma.McpOAuthClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpOAuthClient
   */
  omit?: Prisma.McpOAuthClientOmit<ExtArgs> | null
}
