
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Sell` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Sell
 * 
 */
export type SellModel = runtime.Types.Result.DefaultSelection<Prisma.$SellPayload>

export type AggregateSell = {
  _count: SellCountAggregateOutputType | null
  _avg: SellAvgAggregateOutputType | null
  _sum: SellSumAggregateOutputType | null
  _min: SellMinAggregateOutputType | null
  _max: SellMaxAggregateOutputType | null
}

export type SellAvgAggregateOutputType = {
  quantity: number | null
  finalSellPrice: runtime.Decimal | null
}

export type SellSumAggregateOutputType = {
  quantity: number | null
  finalSellPrice: runtime.Decimal | null
}

export type SellMinAggregateOutputType = {
  id: string | null
  productId: string | null
  storeId: string | null
  customerId: string | null
  staffId: string | null
  quantity: number | null
  finalSellPrice: runtime.Decimal | null
  transactionDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SellMaxAggregateOutputType = {
  id: string | null
  productId: string | null
  storeId: string | null
  customerId: string | null
  staffId: string | null
  quantity: number | null
  finalSellPrice: runtime.Decimal | null
  transactionDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SellCountAggregateOutputType = {
  id: number
  productId: number
  storeId: number
  customerId: number
  staffId: number
  quantity: number
  finalSellPrice: number
  transactionDate: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SellAvgAggregateInputType = {
  quantity?: true
  finalSellPrice?: true
}

export type SellSumAggregateInputType = {
  quantity?: true
  finalSellPrice?: true
}

export type SellMinAggregateInputType = {
  id?: true
  productId?: true
  storeId?: true
  customerId?: true
  staffId?: true
  quantity?: true
  finalSellPrice?: true
  transactionDate?: true
  createdAt?: true
  updatedAt?: true
}

export type SellMaxAggregateInputType = {
  id?: true
  productId?: true
  storeId?: true
  customerId?: true
  staffId?: true
  quantity?: true
  finalSellPrice?: true
  transactionDate?: true
  createdAt?: true
  updatedAt?: true
}

export type SellCountAggregateInputType = {
  id?: true
  productId?: true
  storeId?: true
  customerId?: true
  staffId?: true
  quantity?: true
  finalSellPrice?: true
  transactionDate?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SellAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Sell to aggregate.
   */
  where?: Prisma.SellWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sells to fetch.
   */
  orderBy?: Prisma.SellOrderByWithRelationInput | Prisma.SellOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SellWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sells from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sells.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Sells
  **/
  _count?: true | SellCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SellAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SellSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SellMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SellMaxAggregateInputType
}

export type GetSellAggregateType<T extends SellAggregateArgs> = {
      [P in keyof T & keyof AggregateSell]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSell[P]>
    : Prisma.GetScalarType<T[P], AggregateSell[P]>
}




export type SellGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SellWhereInput
  orderBy?: Prisma.SellOrderByWithAggregationInput | Prisma.SellOrderByWithAggregationInput[]
  by: Prisma.SellScalarFieldEnum[] | Prisma.SellScalarFieldEnum
  having?: Prisma.SellScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SellCountAggregateInputType | true
  _avg?: SellAvgAggregateInputType
  _sum?: SellSumAggregateInputType
  _min?: SellMinAggregateInputType
  _max?: SellMaxAggregateInputType
}

export type SellGroupByOutputType = {
  id: string
  productId: string
  storeId: string
  customerId: string
  staffId: string
  quantity: number
  finalSellPrice: runtime.Decimal
  transactionDate: Date
  createdAt: Date
  updatedAt: Date
  _count: SellCountAggregateOutputType | null
  _avg: SellAvgAggregateOutputType | null
  _sum: SellSumAggregateOutputType | null
  _min: SellMinAggregateOutputType | null
  _max: SellMaxAggregateOutputType | null
}

export type GetSellGroupByPayload<T extends SellGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SellGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SellGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SellGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SellGroupByOutputType[P]>
      }
    >
  >



export type SellWhereInput = {
  AND?: Prisma.SellWhereInput | Prisma.SellWhereInput[]
  OR?: Prisma.SellWhereInput[]
  NOT?: Prisma.SellWhereInput | Prisma.SellWhereInput[]
  id?: Prisma.UuidFilter<"Sell"> | string
  productId?: Prisma.UuidFilter<"Sell"> | string
  storeId?: Prisma.UuidFilter<"Sell"> | string
  customerId?: Prisma.UuidFilter<"Sell"> | string
  staffId?: Prisma.UuidFilter<"Sell"> | string
  quantity?: Prisma.IntFilter<"Sell"> | number
  finalSellPrice?: Prisma.DecimalFilter<"Sell"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFilter<"Sell"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Sell"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Sell"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  store?: Prisma.XOR<Prisma.StoreScalarRelationFilter, Prisma.StoreWhereInput>
  customer?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  staff?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type SellOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  finalSellPrice?: Prisma.SortOrder
  transactionDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
  store?: Prisma.StoreOrderByWithRelationInput
  customer?: Prisma.UserOrderByWithRelationInput
  staff?: Prisma.UserOrderByWithRelationInput
}

export type SellWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SellWhereInput | Prisma.SellWhereInput[]
  OR?: Prisma.SellWhereInput[]
  NOT?: Prisma.SellWhereInput | Prisma.SellWhereInput[]
  productId?: Prisma.UuidFilter<"Sell"> | string
  storeId?: Prisma.UuidFilter<"Sell"> | string
  customerId?: Prisma.UuidFilter<"Sell"> | string
  staffId?: Prisma.UuidFilter<"Sell"> | string
  quantity?: Prisma.IntFilter<"Sell"> | number
  finalSellPrice?: Prisma.DecimalFilter<"Sell"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFilter<"Sell"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Sell"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Sell"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  store?: Prisma.XOR<Prisma.StoreScalarRelationFilter, Prisma.StoreWhereInput>
  customer?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  staff?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type SellOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  finalSellPrice?: Prisma.SortOrder
  transactionDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SellCountOrderByAggregateInput
  _avg?: Prisma.SellAvgOrderByAggregateInput
  _max?: Prisma.SellMaxOrderByAggregateInput
  _min?: Prisma.SellMinOrderByAggregateInput
  _sum?: Prisma.SellSumOrderByAggregateInput
}

export type SellScalarWhereWithAggregatesInput = {
  AND?: Prisma.SellScalarWhereWithAggregatesInput | Prisma.SellScalarWhereWithAggregatesInput[]
  OR?: Prisma.SellScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SellScalarWhereWithAggregatesInput | Prisma.SellScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Sell"> | string
  productId?: Prisma.UuidWithAggregatesFilter<"Sell"> | string
  storeId?: Prisma.UuidWithAggregatesFilter<"Sell"> | string
  customerId?: Prisma.UuidWithAggregatesFilter<"Sell"> | string
  staffId?: Prisma.UuidWithAggregatesFilter<"Sell"> | string
  quantity?: Prisma.IntWithAggregatesFilter<"Sell"> | number
  finalSellPrice?: Prisma.DecimalWithAggregatesFilter<"Sell"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeWithAggregatesFilter<"Sell"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Sell"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Sell"> | Date | string
}

export type SellCreateInput = {
  id?: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutSellsInput
  store: Prisma.StoreCreateNestedOneWithoutSellsInput
  customer: Prisma.UserCreateNestedOneWithoutSellsCustomerInput
  staff: Prisma.UserCreateNestedOneWithoutSellsStaffInput
}

export type SellUncheckedCreateInput = {
  id?: string
  productId: string
  storeId: string
  customerId: string
  staffId: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SellUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutSellsNestedInput
  store?: Prisma.StoreUpdateOneRequiredWithoutSellsNestedInput
  customer?: Prisma.UserUpdateOneRequiredWithoutSellsCustomerNestedInput
  staff?: Prisma.UserUpdateOneRequiredWithoutSellsStaffNestedInput
}

export type SellUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SellCreateManyInput = {
  id?: string
  productId: string
  storeId: string
  customerId: string
  staffId: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SellUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SellUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SellListRelationFilter = {
  every?: Prisma.SellWhereInput
  some?: Prisma.SellWhereInput
  none?: Prisma.SellWhereInput
}

export type SellOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SellCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  finalSellPrice?: Prisma.SortOrder
  transactionDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SellAvgOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
  finalSellPrice?: Prisma.SortOrder
}

export type SellMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  finalSellPrice?: Prisma.SortOrder
  transactionDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SellMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  finalSellPrice?: Prisma.SortOrder
  transactionDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SellSumOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
  finalSellPrice?: Prisma.SortOrder
}

export type SellCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutProductInput, Prisma.SellUncheckedCreateWithoutProductInput> | Prisma.SellCreateWithoutProductInput[] | Prisma.SellUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutProductInput | Prisma.SellCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.SellCreateManyProductInputEnvelope
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
}

export type SellUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutProductInput, Prisma.SellUncheckedCreateWithoutProductInput> | Prisma.SellCreateWithoutProductInput[] | Prisma.SellUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutProductInput | Prisma.SellCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.SellCreateManyProductInputEnvelope
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
}

export type SellUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutProductInput, Prisma.SellUncheckedCreateWithoutProductInput> | Prisma.SellCreateWithoutProductInput[] | Prisma.SellUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutProductInput | Prisma.SellCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.SellUpsertWithWhereUniqueWithoutProductInput | Prisma.SellUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.SellCreateManyProductInputEnvelope
  set?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  disconnect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  delete?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  update?: Prisma.SellUpdateWithWhereUniqueWithoutProductInput | Prisma.SellUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.SellUpdateManyWithWhereWithoutProductInput | Prisma.SellUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.SellScalarWhereInput | Prisma.SellScalarWhereInput[]
}

export type SellUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutProductInput, Prisma.SellUncheckedCreateWithoutProductInput> | Prisma.SellCreateWithoutProductInput[] | Prisma.SellUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutProductInput | Prisma.SellCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.SellUpsertWithWhereUniqueWithoutProductInput | Prisma.SellUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.SellCreateManyProductInputEnvelope
  set?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  disconnect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  delete?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  update?: Prisma.SellUpdateWithWhereUniqueWithoutProductInput | Prisma.SellUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.SellUpdateManyWithWhereWithoutProductInput | Prisma.SellUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.SellScalarWhereInput | Prisma.SellScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type SellCreateNestedManyWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutStoreInput, Prisma.SellUncheckedCreateWithoutStoreInput> | Prisma.SellCreateWithoutStoreInput[] | Prisma.SellUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutStoreInput | Prisma.SellCreateOrConnectWithoutStoreInput[]
  createMany?: Prisma.SellCreateManyStoreInputEnvelope
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
}

export type SellUncheckedCreateNestedManyWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutStoreInput, Prisma.SellUncheckedCreateWithoutStoreInput> | Prisma.SellCreateWithoutStoreInput[] | Prisma.SellUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutStoreInput | Prisma.SellCreateOrConnectWithoutStoreInput[]
  createMany?: Prisma.SellCreateManyStoreInputEnvelope
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
}

export type SellUpdateManyWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutStoreInput, Prisma.SellUncheckedCreateWithoutStoreInput> | Prisma.SellCreateWithoutStoreInput[] | Prisma.SellUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutStoreInput | Prisma.SellCreateOrConnectWithoutStoreInput[]
  upsert?: Prisma.SellUpsertWithWhereUniqueWithoutStoreInput | Prisma.SellUpsertWithWhereUniqueWithoutStoreInput[]
  createMany?: Prisma.SellCreateManyStoreInputEnvelope
  set?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  disconnect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  delete?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  update?: Prisma.SellUpdateWithWhereUniqueWithoutStoreInput | Prisma.SellUpdateWithWhereUniqueWithoutStoreInput[]
  updateMany?: Prisma.SellUpdateManyWithWhereWithoutStoreInput | Prisma.SellUpdateManyWithWhereWithoutStoreInput[]
  deleteMany?: Prisma.SellScalarWhereInput | Prisma.SellScalarWhereInput[]
}

export type SellUncheckedUpdateManyWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutStoreInput, Prisma.SellUncheckedCreateWithoutStoreInput> | Prisma.SellCreateWithoutStoreInput[] | Prisma.SellUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutStoreInput | Prisma.SellCreateOrConnectWithoutStoreInput[]
  upsert?: Prisma.SellUpsertWithWhereUniqueWithoutStoreInput | Prisma.SellUpsertWithWhereUniqueWithoutStoreInput[]
  createMany?: Prisma.SellCreateManyStoreInputEnvelope
  set?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  disconnect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  delete?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  update?: Prisma.SellUpdateWithWhereUniqueWithoutStoreInput | Prisma.SellUpdateWithWhereUniqueWithoutStoreInput[]
  updateMany?: Prisma.SellUpdateManyWithWhereWithoutStoreInput | Prisma.SellUpdateManyWithWhereWithoutStoreInput[]
  deleteMany?: Prisma.SellScalarWhereInput | Prisma.SellScalarWhereInput[]
}

export type SellCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutCustomerInput, Prisma.SellUncheckedCreateWithoutCustomerInput> | Prisma.SellCreateWithoutCustomerInput[] | Prisma.SellUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutCustomerInput | Prisma.SellCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.SellCreateManyCustomerInputEnvelope
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
}

export type SellCreateNestedManyWithoutStaffInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutStaffInput, Prisma.SellUncheckedCreateWithoutStaffInput> | Prisma.SellCreateWithoutStaffInput[] | Prisma.SellUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutStaffInput | Prisma.SellCreateOrConnectWithoutStaffInput[]
  createMany?: Prisma.SellCreateManyStaffInputEnvelope
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
}

export type SellUncheckedCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutCustomerInput, Prisma.SellUncheckedCreateWithoutCustomerInput> | Prisma.SellCreateWithoutCustomerInput[] | Prisma.SellUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutCustomerInput | Prisma.SellCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.SellCreateManyCustomerInputEnvelope
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
}

export type SellUncheckedCreateNestedManyWithoutStaffInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutStaffInput, Prisma.SellUncheckedCreateWithoutStaffInput> | Prisma.SellCreateWithoutStaffInput[] | Prisma.SellUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutStaffInput | Prisma.SellCreateOrConnectWithoutStaffInput[]
  createMany?: Prisma.SellCreateManyStaffInputEnvelope
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
}

export type SellUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutCustomerInput, Prisma.SellUncheckedCreateWithoutCustomerInput> | Prisma.SellCreateWithoutCustomerInput[] | Prisma.SellUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutCustomerInput | Prisma.SellCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.SellUpsertWithWhereUniqueWithoutCustomerInput | Prisma.SellUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.SellCreateManyCustomerInputEnvelope
  set?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  disconnect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  delete?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  update?: Prisma.SellUpdateWithWhereUniqueWithoutCustomerInput | Prisma.SellUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.SellUpdateManyWithWhereWithoutCustomerInput | Prisma.SellUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.SellScalarWhereInput | Prisma.SellScalarWhereInput[]
}

export type SellUpdateManyWithoutStaffNestedInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutStaffInput, Prisma.SellUncheckedCreateWithoutStaffInput> | Prisma.SellCreateWithoutStaffInput[] | Prisma.SellUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutStaffInput | Prisma.SellCreateOrConnectWithoutStaffInput[]
  upsert?: Prisma.SellUpsertWithWhereUniqueWithoutStaffInput | Prisma.SellUpsertWithWhereUniqueWithoutStaffInput[]
  createMany?: Prisma.SellCreateManyStaffInputEnvelope
  set?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  disconnect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  delete?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  update?: Prisma.SellUpdateWithWhereUniqueWithoutStaffInput | Prisma.SellUpdateWithWhereUniqueWithoutStaffInput[]
  updateMany?: Prisma.SellUpdateManyWithWhereWithoutStaffInput | Prisma.SellUpdateManyWithWhereWithoutStaffInput[]
  deleteMany?: Prisma.SellScalarWhereInput | Prisma.SellScalarWhereInput[]
}

export type SellUncheckedUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutCustomerInput, Prisma.SellUncheckedCreateWithoutCustomerInput> | Prisma.SellCreateWithoutCustomerInput[] | Prisma.SellUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutCustomerInput | Prisma.SellCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.SellUpsertWithWhereUniqueWithoutCustomerInput | Prisma.SellUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.SellCreateManyCustomerInputEnvelope
  set?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  disconnect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  delete?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  update?: Prisma.SellUpdateWithWhereUniqueWithoutCustomerInput | Prisma.SellUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.SellUpdateManyWithWhereWithoutCustomerInput | Prisma.SellUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.SellScalarWhereInput | Prisma.SellScalarWhereInput[]
}

export type SellUncheckedUpdateManyWithoutStaffNestedInput = {
  create?: Prisma.XOR<Prisma.SellCreateWithoutStaffInput, Prisma.SellUncheckedCreateWithoutStaffInput> | Prisma.SellCreateWithoutStaffInput[] | Prisma.SellUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.SellCreateOrConnectWithoutStaffInput | Prisma.SellCreateOrConnectWithoutStaffInput[]
  upsert?: Prisma.SellUpsertWithWhereUniqueWithoutStaffInput | Prisma.SellUpsertWithWhereUniqueWithoutStaffInput[]
  createMany?: Prisma.SellCreateManyStaffInputEnvelope
  set?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  disconnect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  delete?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  connect?: Prisma.SellWhereUniqueInput | Prisma.SellWhereUniqueInput[]
  update?: Prisma.SellUpdateWithWhereUniqueWithoutStaffInput | Prisma.SellUpdateWithWhereUniqueWithoutStaffInput[]
  updateMany?: Prisma.SellUpdateManyWithWhereWithoutStaffInput | Prisma.SellUpdateManyWithWhereWithoutStaffInput[]
  deleteMany?: Prisma.SellScalarWhereInput | Prisma.SellScalarWhereInput[]
}

export type SellCreateWithoutProductInput = {
  id?: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  store: Prisma.StoreCreateNestedOneWithoutSellsInput
  customer: Prisma.UserCreateNestedOneWithoutSellsCustomerInput
  staff: Prisma.UserCreateNestedOneWithoutSellsStaffInput
}

export type SellUncheckedCreateWithoutProductInput = {
  id?: string
  storeId: string
  customerId: string
  staffId: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SellCreateOrConnectWithoutProductInput = {
  where: Prisma.SellWhereUniqueInput
  create: Prisma.XOR<Prisma.SellCreateWithoutProductInput, Prisma.SellUncheckedCreateWithoutProductInput>
}

export type SellCreateManyProductInputEnvelope = {
  data: Prisma.SellCreateManyProductInput | Prisma.SellCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type SellUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.SellWhereUniqueInput
  update: Prisma.XOR<Prisma.SellUpdateWithoutProductInput, Prisma.SellUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.SellCreateWithoutProductInput, Prisma.SellUncheckedCreateWithoutProductInput>
}

export type SellUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.SellWhereUniqueInput
  data: Prisma.XOR<Prisma.SellUpdateWithoutProductInput, Prisma.SellUncheckedUpdateWithoutProductInput>
}

export type SellUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.SellScalarWhereInput
  data: Prisma.XOR<Prisma.SellUpdateManyMutationInput, Prisma.SellUncheckedUpdateManyWithoutProductInput>
}

export type SellScalarWhereInput = {
  AND?: Prisma.SellScalarWhereInput | Prisma.SellScalarWhereInput[]
  OR?: Prisma.SellScalarWhereInput[]
  NOT?: Prisma.SellScalarWhereInput | Prisma.SellScalarWhereInput[]
  id?: Prisma.UuidFilter<"Sell"> | string
  productId?: Prisma.UuidFilter<"Sell"> | string
  storeId?: Prisma.UuidFilter<"Sell"> | string
  customerId?: Prisma.UuidFilter<"Sell"> | string
  staffId?: Prisma.UuidFilter<"Sell"> | string
  quantity?: Prisma.IntFilter<"Sell"> | number
  finalSellPrice?: Prisma.DecimalFilter<"Sell"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFilter<"Sell"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Sell"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Sell"> | Date | string
}

export type SellCreateWithoutStoreInput = {
  id?: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutSellsInput
  customer: Prisma.UserCreateNestedOneWithoutSellsCustomerInput
  staff: Prisma.UserCreateNestedOneWithoutSellsStaffInput
}

export type SellUncheckedCreateWithoutStoreInput = {
  id?: string
  productId: string
  customerId: string
  staffId: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SellCreateOrConnectWithoutStoreInput = {
  where: Prisma.SellWhereUniqueInput
  create: Prisma.XOR<Prisma.SellCreateWithoutStoreInput, Prisma.SellUncheckedCreateWithoutStoreInput>
}

export type SellCreateManyStoreInputEnvelope = {
  data: Prisma.SellCreateManyStoreInput | Prisma.SellCreateManyStoreInput[]
  skipDuplicates?: boolean
}

export type SellUpsertWithWhereUniqueWithoutStoreInput = {
  where: Prisma.SellWhereUniqueInput
  update: Prisma.XOR<Prisma.SellUpdateWithoutStoreInput, Prisma.SellUncheckedUpdateWithoutStoreInput>
  create: Prisma.XOR<Prisma.SellCreateWithoutStoreInput, Prisma.SellUncheckedCreateWithoutStoreInput>
}

export type SellUpdateWithWhereUniqueWithoutStoreInput = {
  where: Prisma.SellWhereUniqueInput
  data: Prisma.XOR<Prisma.SellUpdateWithoutStoreInput, Prisma.SellUncheckedUpdateWithoutStoreInput>
}

export type SellUpdateManyWithWhereWithoutStoreInput = {
  where: Prisma.SellScalarWhereInput
  data: Prisma.XOR<Prisma.SellUpdateManyMutationInput, Prisma.SellUncheckedUpdateManyWithoutStoreInput>
}

export type SellCreateWithoutCustomerInput = {
  id?: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutSellsInput
  store: Prisma.StoreCreateNestedOneWithoutSellsInput
  staff: Prisma.UserCreateNestedOneWithoutSellsStaffInput
}

export type SellUncheckedCreateWithoutCustomerInput = {
  id?: string
  productId: string
  storeId: string
  staffId: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SellCreateOrConnectWithoutCustomerInput = {
  where: Prisma.SellWhereUniqueInput
  create: Prisma.XOR<Prisma.SellCreateWithoutCustomerInput, Prisma.SellUncheckedCreateWithoutCustomerInput>
}

export type SellCreateManyCustomerInputEnvelope = {
  data: Prisma.SellCreateManyCustomerInput | Prisma.SellCreateManyCustomerInput[]
  skipDuplicates?: boolean
}

export type SellCreateWithoutStaffInput = {
  id?: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutSellsInput
  store: Prisma.StoreCreateNestedOneWithoutSellsInput
  customer: Prisma.UserCreateNestedOneWithoutSellsCustomerInput
}

export type SellUncheckedCreateWithoutStaffInput = {
  id?: string
  productId: string
  storeId: string
  customerId: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SellCreateOrConnectWithoutStaffInput = {
  where: Prisma.SellWhereUniqueInput
  create: Prisma.XOR<Prisma.SellCreateWithoutStaffInput, Prisma.SellUncheckedCreateWithoutStaffInput>
}

export type SellCreateManyStaffInputEnvelope = {
  data: Prisma.SellCreateManyStaffInput | Prisma.SellCreateManyStaffInput[]
  skipDuplicates?: boolean
}

export type SellUpsertWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.SellWhereUniqueInput
  update: Prisma.XOR<Prisma.SellUpdateWithoutCustomerInput, Prisma.SellUncheckedUpdateWithoutCustomerInput>
  create: Prisma.XOR<Prisma.SellCreateWithoutCustomerInput, Prisma.SellUncheckedCreateWithoutCustomerInput>
}

export type SellUpdateWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.SellWhereUniqueInput
  data: Prisma.XOR<Prisma.SellUpdateWithoutCustomerInput, Prisma.SellUncheckedUpdateWithoutCustomerInput>
}

export type SellUpdateManyWithWhereWithoutCustomerInput = {
  where: Prisma.SellScalarWhereInput
  data: Prisma.XOR<Prisma.SellUpdateManyMutationInput, Prisma.SellUncheckedUpdateManyWithoutCustomerInput>
}

export type SellUpsertWithWhereUniqueWithoutStaffInput = {
  where: Prisma.SellWhereUniqueInput
  update: Prisma.XOR<Prisma.SellUpdateWithoutStaffInput, Prisma.SellUncheckedUpdateWithoutStaffInput>
  create: Prisma.XOR<Prisma.SellCreateWithoutStaffInput, Prisma.SellUncheckedCreateWithoutStaffInput>
}

export type SellUpdateWithWhereUniqueWithoutStaffInput = {
  where: Prisma.SellWhereUniqueInput
  data: Prisma.XOR<Prisma.SellUpdateWithoutStaffInput, Prisma.SellUncheckedUpdateWithoutStaffInput>
}

export type SellUpdateManyWithWhereWithoutStaffInput = {
  where: Prisma.SellScalarWhereInput
  data: Prisma.XOR<Prisma.SellUpdateManyMutationInput, Prisma.SellUncheckedUpdateManyWithoutStaffInput>
}

export type SellCreateManyProductInput = {
  id?: string
  storeId: string
  customerId: string
  staffId: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SellUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  store?: Prisma.StoreUpdateOneRequiredWithoutSellsNestedInput
  customer?: Prisma.UserUpdateOneRequiredWithoutSellsCustomerNestedInput
  staff?: Prisma.UserUpdateOneRequiredWithoutSellsStaffNestedInput
}

export type SellUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SellUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SellCreateManyStoreInput = {
  id?: string
  productId: string
  customerId: string
  staffId: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SellUpdateWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutSellsNestedInput
  customer?: Prisma.UserUpdateOneRequiredWithoutSellsCustomerNestedInput
  staff?: Prisma.UserUpdateOneRequiredWithoutSellsStaffNestedInput
}

export type SellUncheckedUpdateWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SellUncheckedUpdateManyWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SellCreateManyCustomerInput = {
  id?: string
  productId: string
  storeId: string
  staffId: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SellCreateManyStaffInput = {
  id?: string
  productId: string
  storeId: string
  customerId: string
  quantity: number
  finalSellPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SellUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutSellsNestedInput
  store?: Prisma.StoreUpdateOneRequiredWithoutSellsNestedInput
  staff?: Prisma.UserUpdateOneRequiredWithoutSellsStaffNestedInput
}

export type SellUncheckedUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SellUncheckedUpdateManyWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SellUpdateWithoutStaffInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutSellsNestedInput
  store?: Prisma.StoreUpdateOneRequiredWithoutSellsNestedInput
  customer?: Prisma.UserUpdateOneRequiredWithoutSellsCustomerNestedInput
}

export type SellUncheckedUpdateWithoutStaffInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SellUncheckedUpdateManyWithoutStaffInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  storeId?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalSellPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  transactionDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SellSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  storeId?: boolean
  customerId?: boolean
  staffId?: boolean
  quantity?: boolean
  finalSellPrice?: boolean
  transactionDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
  customer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  staff?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sell"]>

export type SellSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  storeId?: boolean
  customerId?: boolean
  staffId?: boolean
  quantity?: boolean
  finalSellPrice?: boolean
  transactionDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
  customer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  staff?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sell"]>

export type SellSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  storeId?: boolean
  customerId?: boolean
  staffId?: boolean
  quantity?: boolean
  finalSellPrice?: boolean
  transactionDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
  customer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  staff?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sell"]>

export type SellSelectScalar = {
  id?: boolean
  productId?: boolean
  storeId?: boolean
  customerId?: boolean
  staffId?: boolean
  quantity?: boolean
  finalSellPrice?: boolean
  transactionDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SellOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productId" | "storeId" | "customerId" | "staffId" | "quantity" | "finalSellPrice" | "transactionDate" | "createdAt" | "updatedAt", ExtArgs["result"]["sell"]>
export type SellInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
  customer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  staff?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SellIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
  customer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  staff?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SellIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
  customer?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  staff?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $SellPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Sell"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
    store: Prisma.$StorePayload<ExtArgs>
    customer: Prisma.$UserPayload<ExtArgs>
    staff: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    productId: string
    storeId: string
    customerId: string
    staffId: string
    quantity: number
    finalSellPrice: runtime.Decimal
    transactionDate: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["sell"]>
  composites: {}
}

export type SellGetPayload<S extends boolean | null | undefined | SellDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SellPayload, S>

export type SellCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SellFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SellCountAggregateInputType | true
  }

export interface SellDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Sell'], meta: { name: 'Sell' } }
  /**
   * Find zero or one Sell that matches the filter.
   * @param {SellFindUniqueArgs} args - Arguments to find a Sell
   * @example
   * // Get one Sell
   * const sell = await prisma.sell.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SellFindUniqueArgs>(args: Prisma.SelectSubset<T, SellFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SellClient<runtime.Types.Result.GetResult<Prisma.$SellPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Sell that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SellFindUniqueOrThrowArgs} args - Arguments to find a Sell
   * @example
   * // Get one Sell
   * const sell = await prisma.sell.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SellFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SellFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SellClient<runtime.Types.Result.GetResult<Prisma.$SellPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Sell that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellFindFirstArgs} args - Arguments to find a Sell
   * @example
   * // Get one Sell
   * const sell = await prisma.sell.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SellFindFirstArgs>(args?: Prisma.SelectSubset<T, SellFindFirstArgs<ExtArgs>>): Prisma.Prisma__SellClient<runtime.Types.Result.GetResult<Prisma.$SellPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Sell that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellFindFirstOrThrowArgs} args - Arguments to find a Sell
   * @example
   * // Get one Sell
   * const sell = await prisma.sell.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SellFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SellFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SellClient<runtime.Types.Result.GetResult<Prisma.$SellPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Sells that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Sells
   * const sells = await prisma.sell.findMany()
   * 
   * // Get first 10 Sells
   * const sells = await prisma.sell.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sellWithIdOnly = await prisma.sell.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SellFindManyArgs>(args?: Prisma.SelectSubset<T, SellFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SellPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Sell.
   * @param {SellCreateArgs} args - Arguments to create a Sell.
   * @example
   * // Create one Sell
   * const Sell = await prisma.sell.create({
   *   data: {
   *     // ... data to create a Sell
   *   }
   * })
   * 
   */
  create<T extends SellCreateArgs>(args: Prisma.SelectSubset<T, SellCreateArgs<ExtArgs>>): Prisma.Prisma__SellClient<runtime.Types.Result.GetResult<Prisma.$SellPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Sells.
   * @param {SellCreateManyArgs} args - Arguments to create many Sells.
   * @example
   * // Create many Sells
   * const sell = await prisma.sell.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SellCreateManyArgs>(args?: Prisma.SelectSubset<T, SellCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Sells and returns the data saved in the database.
   * @param {SellCreateManyAndReturnArgs} args - Arguments to create many Sells.
   * @example
   * // Create many Sells
   * const sell = await prisma.sell.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Sells and only return the `id`
   * const sellWithIdOnly = await prisma.sell.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SellCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SellCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SellPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Sell.
   * @param {SellDeleteArgs} args - Arguments to delete one Sell.
   * @example
   * // Delete one Sell
   * const Sell = await prisma.sell.delete({
   *   where: {
   *     // ... filter to delete one Sell
   *   }
   * })
   * 
   */
  delete<T extends SellDeleteArgs>(args: Prisma.SelectSubset<T, SellDeleteArgs<ExtArgs>>): Prisma.Prisma__SellClient<runtime.Types.Result.GetResult<Prisma.$SellPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Sell.
   * @param {SellUpdateArgs} args - Arguments to update one Sell.
   * @example
   * // Update one Sell
   * const sell = await prisma.sell.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SellUpdateArgs>(args: Prisma.SelectSubset<T, SellUpdateArgs<ExtArgs>>): Prisma.Prisma__SellClient<runtime.Types.Result.GetResult<Prisma.$SellPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Sells.
   * @param {SellDeleteManyArgs} args - Arguments to filter Sells to delete.
   * @example
   * // Delete a few Sells
   * const { count } = await prisma.sell.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SellDeleteManyArgs>(args?: Prisma.SelectSubset<T, SellDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sells.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Sells
   * const sell = await prisma.sell.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SellUpdateManyArgs>(args: Prisma.SelectSubset<T, SellUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sells and returns the data updated in the database.
   * @param {SellUpdateManyAndReturnArgs} args - Arguments to update many Sells.
   * @example
   * // Update many Sells
   * const sell = await prisma.sell.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Sells and only return the `id`
   * const sellWithIdOnly = await prisma.sell.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SellUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SellUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SellPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Sell.
   * @param {SellUpsertArgs} args - Arguments to update or create a Sell.
   * @example
   * // Update or create a Sell
   * const sell = await prisma.sell.upsert({
   *   create: {
   *     // ... data to create a Sell
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Sell we want to update
   *   }
   * })
   */
  upsert<T extends SellUpsertArgs>(args: Prisma.SelectSubset<T, SellUpsertArgs<ExtArgs>>): Prisma.Prisma__SellClient<runtime.Types.Result.GetResult<Prisma.$SellPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Sells.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellCountArgs} args - Arguments to filter Sells to count.
   * @example
   * // Count the number of Sells
   * const count = await prisma.sell.count({
   *   where: {
   *     // ... the filter for the Sells we want to count
   *   }
   * })
  **/
  count<T extends SellCountArgs>(
    args?: Prisma.Subset<T, SellCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SellCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Sell.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SellAggregateArgs>(args: Prisma.Subset<T, SellAggregateArgs>): Prisma.PrismaPromise<GetSellAggregateType<T>>

  /**
   * Group by Sell.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SellGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SellGroupByArgs['orderBy'] }
      : { orderBy?: SellGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SellGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSellGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Sell model
 */
readonly fields: SellFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Sell.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SellClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  store<T extends Prisma.StoreDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StoreDefaultArgs<ExtArgs>>): Prisma.Prisma__StoreClient<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  customer<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  staff<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Sell model
 */
export interface SellFieldRefs {
  readonly id: Prisma.FieldRef<"Sell", 'String'>
  readonly productId: Prisma.FieldRef<"Sell", 'String'>
  readonly storeId: Prisma.FieldRef<"Sell", 'String'>
  readonly customerId: Prisma.FieldRef<"Sell", 'String'>
  readonly staffId: Prisma.FieldRef<"Sell", 'String'>
  readonly quantity: Prisma.FieldRef<"Sell", 'Int'>
  readonly finalSellPrice: Prisma.FieldRef<"Sell", 'Decimal'>
  readonly transactionDate: Prisma.FieldRef<"Sell", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Sell", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Sell", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Sell findUnique
 */
export type SellFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sell
   */
  select?: Prisma.SellSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sell
   */
  omit?: Prisma.SellOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellInclude<ExtArgs> | null
  /**
   * Filter, which Sell to fetch.
   */
  where: Prisma.SellWhereUniqueInput
}

/**
 * Sell findUniqueOrThrow
 */
export type SellFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sell
   */
  select?: Prisma.SellSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sell
   */
  omit?: Prisma.SellOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellInclude<ExtArgs> | null
  /**
   * Filter, which Sell to fetch.
   */
  where: Prisma.SellWhereUniqueInput
}

/**
 * Sell findFirst
 */
export type SellFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sell
   */
  select?: Prisma.SellSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sell
   */
  omit?: Prisma.SellOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellInclude<ExtArgs> | null
  /**
   * Filter, which Sell to fetch.
   */
  where?: Prisma.SellWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sells to fetch.
   */
  orderBy?: Prisma.SellOrderByWithRelationInput | Prisma.SellOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Sells.
   */
  cursor?: Prisma.SellWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sells from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sells.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sells.
   */
  distinct?: Prisma.SellScalarFieldEnum | Prisma.SellScalarFieldEnum[]
}

/**
 * Sell findFirstOrThrow
 */
export type SellFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sell
   */
  select?: Prisma.SellSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sell
   */
  omit?: Prisma.SellOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellInclude<ExtArgs> | null
  /**
   * Filter, which Sell to fetch.
   */
  where?: Prisma.SellWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sells to fetch.
   */
  orderBy?: Prisma.SellOrderByWithRelationInput | Prisma.SellOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Sells.
   */
  cursor?: Prisma.SellWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sells from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sells.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sells.
   */
  distinct?: Prisma.SellScalarFieldEnum | Prisma.SellScalarFieldEnum[]
}

/**
 * Sell findMany
 */
export type SellFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sell
   */
  select?: Prisma.SellSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sell
   */
  omit?: Prisma.SellOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellInclude<ExtArgs> | null
  /**
   * Filter, which Sells to fetch.
   */
  where?: Prisma.SellWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sells to fetch.
   */
  orderBy?: Prisma.SellOrderByWithRelationInput | Prisma.SellOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Sells.
   */
  cursor?: Prisma.SellWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sells from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sells.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sells.
   */
  distinct?: Prisma.SellScalarFieldEnum | Prisma.SellScalarFieldEnum[]
}

/**
 * Sell create
 */
export type SellCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sell
   */
  select?: Prisma.SellSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sell
   */
  omit?: Prisma.SellOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellInclude<ExtArgs> | null
  /**
   * The data needed to create a Sell.
   */
  data: Prisma.XOR<Prisma.SellCreateInput, Prisma.SellUncheckedCreateInput>
}

/**
 * Sell createMany
 */
export type SellCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Sells.
   */
  data: Prisma.SellCreateManyInput | Prisma.SellCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Sell createManyAndReturn
 */
export type SellCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sell
   */
  select?: Prisma.SellSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Sell
   */
  omit?: Prisma.SellOmit<ExtArgs> | null
  /**
   * The data used to create many Sells.
   */
  data: Prisma.SellCreateManyInput | Prisma.SellCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Sell update
 */
export type SellUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sell
   */
  select?: Prisma.SellSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sell
   */
  omit?: Prisma.SellOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellInclude<ExtArgs> | null
  /**
   * The data needed to update a Sell.
   */
  data: Prisma.XOR<Prisma.SellUpdateInput, Prisma.SellUncheckedUpdateInput>
  /**
   * Choose, which Sell to update.
   */
  where: Prisma.SellWhereUniqueInput
}

/**
 * Sell updateMany
 */
export type SellUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Sells.
   */
  data: Prisma.XOR<Prisma.SellUpdateManyMutationInput, Prisma.SellUncheckedUpdateManyInput>
  /**
   * Filter which Sells to update
   */
  where?: Prisma.SellWhereInput
  /**
   * Limit how many Sells to update.
   */
  limit?: number
}

/**
 * Sell updateManyAndReturn
 */
export type SellUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sell
   */
  select?: Prisma.SellSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Sell
   */
  omit?: Prisma.SellOmit<ExtArgs> | null
  /**
   * The data used to update Sells.
   */
  data: Prisma.XOR<Prisma.SellUpdateManyMutationInput, Prisma.SellUncheckedUpdateManyInput>
  /**
   * Filter which Sells to update
   */
  where?: Prisma.SellWhereInput
  /**
   * Limit how many Sells to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Sell upsert
 */
export type SellUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sell
   */
  select?: Prisma.SellSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sell
   */
  omit?: Prisma.SellOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellInclude<ExtArgs> | null
  /**
   * The filter to search for the Sell to update in case it exists.
   */
  where: Prisma.SellWhereUniqueInput
  /**
   * In case the Sell found by the `where` argument doesn't exist, create a new Sell with this data.
   */
  create: Prisma.XOR<Prisma.SellCreateInput, Prisma.SellUncheckedCreateInput>
  /**
   * In case the Sell was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SellUpdateInput, Prisma.SellUncheckedUpdateInput>
}

/**
 * Sell delete
 */
export type SellDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sell
   */
  select?: Prisma.SellSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sell
   */
  omit?: Prisma.SellOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellInclude<ExtArgs> | null
  /**
   * Filter which Sell to delete.
   */
  where: Prisma.SellWhereUniqueInput
}

/**
 * Sell deleteMany
 */
export type SellDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Sells to delete
   */
  where?: Prisma.SellWhereInput
  /**
   * Limit how many Sells to delete.
   */
  limit?: number
}

/**
 * Sell without action
 */
export type SellDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sell
   */
  select?: Prisma.SellSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sell
   */
  omit?: Prisma.SellOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellInclude<ExtArgs> | null
}
