
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SellItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SellItem
 * 
 */
export type SellItemModel = runtime.Types.Result.DefaultSelection<Prisma.$SellItemPayload>

export type AggregateSellItem = {
  _count: SellItemCountAggregateOutputType | null
  _avg: SellItemAvgAggregateOutputType | null
  _sum: SellItemSumAggregateOutputType | null
  _min: SellItemMinAggregateOutputType | null
  _max: SellItemMaxAggregateOutputType | null
}

export type SellItemAvgAggregateOutputType = {
  quantity: number | null
  finalPrice: runtime.Decimal | null
}

export type SellItemSumAggregateOutputType = {
  quantity: number | null
  finalPrice: runtime.Decimal | null
}

export type SellItemMinAggregateOutputType = {
  id: string | null
  sellId: string | null
  productId: string | null
  quantity: number | null
  finalPrice: runtime.Decimal | null
}

export type SellItemMaxAggregateOutputType = {
  id: string | null
  sellId: string | null
  productId: string | null
  quantity: number | null
  finalPrice: runtime.Decimal | null
}

export type SellItemCountAggregateOutputType = {
  id: number
  sellId: number
  productId: number
  quantity: number
  finalPrice: number
  _all: number
}


export type SellItemAvgAggregateInputType = {
  quantity?: true
  finalPrice?: true
}

export type SellItemSumAggregateInputType = {
  quantity?: true
  finalPrice?: true
}

export type SellItemMinAggregateInputType = {
  id?: true
  sellId?: true
  productId?: true
  quantity?: true
  finalPrice?: true
}

export type SellItemMaxAggregateInputType = {
  id?: true
  sellId?: true
  productId?: true
  quantity?: true
  finalPrice?: true
}

export type SellItemCountAggregateInputType = {
  id?: true
  sellId?: true
  productId?: true
  quantity?: true
  finalPrice?: true
  _all?: true
}

export type SellItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SellItem to aggregate.
   */
  where?: Prisma.SellItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SellItems to fetch.
   */
  orderBy?: Prisma.SellItemOrderByWithRelationInput | Prisma.SellItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SellItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SellItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SellItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SellItems
  **/
  _count?: true | SellItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SellItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SellItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SellItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SellItemMaxAggregateInputType
}

export type GetSellItemAggregateType<T extends SellItemAggregateArgs> = {
      [P in keyof T & keyof AggregateSellItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSellItem[P]>
    : Prisma.GetScalarType<T[P], AggregateSellItem[P]>
}




export type SellItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SellItemWhereInput
  orderBy?: Prisma.SellItemOrderByWithAggregationInput | Prisma.SellItemOrderByWithAggregationInput[]
  by: Prisma.SellItemScalarFieldEnum[] | Prisma.SellItemScalarFieldEnum
  having?: Prisma.SellItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SellItemCountAggregateInputType | true
  _avg?: SellItemAvgAggregateInputType
  _sum?: SellItemSumAggregateInputType
  _min?: SellItemMinAggregateInputType
  _max?: SellItemMaxAggregateInputType
}

export type SellItemGroupByOutputType = {
  id: string
  sellId: string
  productId: string
  quantity: number
  finalPrice: runtime.Decimal
  _count: SellItemCountAggregateOutputType | null
  _avg: SellItemAvgAggregateOutputType | null
  _sum: SellItemSumAggregateOutputType | null
  _min: SellItemMinAggregateOutputType | null
  _max: SellItemMaxAggregateOutputType | null
}

export type GetSellItemGroupByPayload<T extends SellItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SellItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SellItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SellItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SellItemGroupByOutputType[P]>
      }
    >
  >



export type SellItemWhereInput = {
  AND?: Prisma.SellItemWhereInput | Prisma.SellItemWhereInput[]
  OR?: Prisma.SellItemWhereInput[]
  NOT?: Prisma.SellItemWhereInput | Prisma.SellItemWhereInput[]
  id?: Prisma.UuidFilter<"SellItem"> | string
  sellId?: Prisma.UuidFilter<"SellItem"> | string
  productId?: Prisma.UuidFilter<"SellItem"> | string
  quantity?: Prisma.IntFilter<"SellItem"> | number
  finalPrice?: Prisma.DecimalFilter<"SellItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sell?: Prisma.XOR<Prisma.SellScalarRelationFilter, Prisma.SellWhereInput>
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type SellItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sellId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  finalPrice?: Prisma.SortOrder
  sell?: Prisma.SellOrderByWithRelationInput
  product?: Prisma.ProductOrderByWithRelationInput
}

export type SellItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SellItemWhereInput | Prisma.SellItemWhereInput[]
  OR?: Prisma.SellItemWhereInput[]
  NOT?: Prisma.SellItemWhereInput | Prisma.SellItemWhereInput[]
  sellId?: Prisma.UuidFilter<"SellItem"> | string
  productId?: Prisma.UuidFilter<"SellItem"> | string
  quantity?: Prisma.IntFilter<"SellItem"> | number
  finalPrice?: Prisma.DecimalFilter<"SellItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  sell?: Prisma.XOR<Prisma.SellScalarRelationFilter, Prisma.SellWhereInput>
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id">

export type SellItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sellId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  finalPrice?: Prisma.SortOrder
  _count?: Prisma.SellItemCountOrderByAggregateInput
  _avg?: Prisma.SellItemAvgOrderByAggregateInput
  _max?: Prisma.SellItemMaxOrderByAggregateInput
  _min?: Prisma.SellItemMinOrderByAggregateInput
  _sum?: Prisma.SellItemSumOrderByAggregateInput
}

export type SellItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.SellItemScalarWhereWithAggregatesInput | Prisma.SellItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.SellItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SellItemScalarWhereWithAggregatesInput | Prisma.SellItemScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"SellItem"> | string
  sellId?: Prisma.UuidWithAggregatesFilter<"SellItem"> | string
  productId?: Prisma.UuidWithAggregatesFilter<"SellItem"> | string
  quantity?: Prisma.IntWithAggregatesFilter<"SellItem"> | number
  finalPrice?: Prisma.DecimalWithAggregatesFilter<"SellItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemCreateInput = {
  id?: string
  quantity: number
  finalPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  sell: Prisma.SellCreateNestedOneWithoutCartInput
  product: Prisma.ProductCreateNestedOneWithoutSellItemsInput
}

export type SellItemUncheckedCreateInput = {
  id?: string
  sellId: string
  productId: string
  quantity: number
  finalPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sell?: Prisma.SellUpdateOneRequiredWithoutCartNestedInput
  product?: Prisma.ProductUpdateOneRequiredWithoutSellItemsNestedInput
}

export type SellItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sellId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemCreateManyInput = {
  id?: string
  sellId: string
  productId: string
  quantity: number
  finalPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sellId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemListRelationFilter = {
  every?: Prisma.SellItemWhereInput
  some?: Prisma.SellItemWhereInput
  none?: Prisma.SellItemWhereInput
}

export type SellItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SellItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sellId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  finalPrice?: Prisma.SortOrder
}

export type SellItemAvgOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
  finalPrice?: Prisma.SortOrder
}

export type SellItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sellId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  finalPrice?: Prisma.SortOrder
}

export type SellItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sellId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  finalPrice?: Prisma.SortOrder
}

export type SellItemSumOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
  finalPrice?: Prisma.SortOrder
}

export type SellItemCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.SellItemCreateWithoutProductInput, Prisma.SellItemUncheckedCreateWithoutProductInput> | Prisma.SellItemCreateWithoutProductInput[] | Prisma.SellItemUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.SellItemCreateOrConnectWithoutProductInput | Prisma.SellItemCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.SellItemCreateManyProductInputEnvelope
  connect?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
}

export type SellItemUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.SellItemCreateWithoutProductInput, Prisma.SellItemUncheckedCreateWithoutProductInput> | Prisma.SellItemCreateWithoutProductInput[] | Prisma.SellItemUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.SellItemCreateOrConnectWithoutProductInput | Prisma.SellItemCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.SellItemCreateManyProductInputEnvelope
  connect?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
}

export type SellItemUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.SellItemCreateWithoutProductInput, Prisma.SellItemUncheckedCreateWithoutProductInput> | Prisma.SellItemCreateWithoutProductInput[] | Prisma.SellItemUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.SellItemCreateOrConnectWithoutProductInput | Prisma.SellItemCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.SellItemUpsertWithWhereUniqueWithoutProductInput | Prisma.SellItemUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.SellItemCreateManyProductInputEnvelope
  set?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  disconnect?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  delete?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  connect?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  update?: Prisma.SellItemUpdateWithWhereUniqueWithoutProductInput | Prisma.SellItemUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.SellItemUpdateManyWithWhereWithoutProductInput | Prisma.SellItemUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.SellItemScalarWhereInput | Prisma.SellItemScalarWhereInput[]
}

export type SellItemUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.SellItemCreateWithoutProductInput, Prisma.SellItemUncheckedCreateWithoutProductInput> | Prisma.SellItemCreateWithoutProductInput[] | Prisma.SellItemUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.SellItemCreateOrConnectWithoutProductInput | Prisma.SellItemCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.SellItemUpsertWithWhereUniqueWithoutProductInput | Prisma.SellItemUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.SellItemCreateManyProductInputEnvelope
  set?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  disconnect?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  delete?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  connect?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  update?: Prisma.SellItemUpdateWithWhereUniqueWithoutProductInput | Prisma.SellItemUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.SellItemUpdateManyWithWhereWithoutProductInput | Prisma.SellItemUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.SellItemScalarWhereInput | Prisma.SellItemScalarWhereInput[]
}

export type SellItemCreateNestedManyWithoutSellInput = {
  create?: Prisma.XOR<Prisma.SellItemCreateWithoutSellInput, Prisma.SellItemUncheckedCreateWithoutSellInput> | Prisma.SellItemCreateWithoutSellInput[] | Prisma.SellItemUncheckedCreateWithoutSellInput[]
  connectOrCreate?: Prisma.SellItemCreateOrConnectWithoutSellInput | Prisma.SellItemCreateOrConnectWithoutSellInput[]
  createMany?: Prisma.SellItemCreateManySellInputEnvelope
  connect?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
}

export type SellItemUncheckedCreateNestedManyWithoutSellInput = {
  create?: Prisma.XOR<Prisma.SellItemCreateWithoutSellInput, Prisma.SellItemUncheckedCreateWithoutSellInput> | Prisma.SellItemCreateWithoutSellInput[] | Prisma.SellItemUncheckedCreateWithoutSellInput[]
  connectOrCreate?: Prisma.SellItemCreateOrConnectWithoutSellInput | Prisma.SellItemCreateOrConnectWithoutSellInput[]
  createMany?: Prisma.SellItemCreateManySellInputEnvelope
  connect?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
}

export type SellItemUpdateManyWithoutSellNestedInput = {
  create?: Prisma.XOR<Prisma.SellItemCreateWithoutSellInput, Prisma.SellItemUncheckedCreateWithoutSellInput> | Prisma.SellItemCreateWithoutSellInput[] | Prisma.SellItemUncheckedCreateWithoutSellInput[]
  connectOrCreate?: Prisma.SellItemCreateOrConnectWithoutSellInput | Prisma.SellItemCreateOrConnectWithoutSellInput[]
  upsert?: Prisma.SellItemUpsertWithWhereUniqueWithoutSellInput | Prisma.SellItemUpsertWithWhereUniqueWithoutSellInput[]
  createMany?: Prisma.SellItemCreateManySellInputEnvelope
  set?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  disconnect?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  delete?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  connect?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  update?: Prisma.SellItemUpdateWithWhereUniqueWithoutSellInput | Prisma.SellItemUpdateWithWhereUniqueWithoutSellInput[]
  updateMany?: Prisma.SellItemUpdateManyWithWhereWithoutSellInput | Prisma.SellItemUpdateManyWithWhereWithoutSellInput[]
  deleteMany?: Prisma.SellItemScalarWhereInput | Prisma.SellItemScalarWhereInput[]
}

export type SellItemUncheckedUpdateManyWithoutSellNestedInput = {
  create?: Prisma.XOR<Prisma.SellItemCreateWithoutSellInput, Prisma.SellItemUncheckedCreateWithoutSellInput> | Prisma.SellItemCreateWithoutSellInput[] | Prisma.SellItemUncheckedCreateWithoutSellInput[]
  connectOrCreate?: Prisma.SellItemCreateOrConnectWithoutSellInput | Prisma.SellItemCreateOrConnectWithoutSellInput[]
  upsert?: Prisma.SellItemUpsertWithWhereUniqueWithoutSellInput | Prisma.SellItemUpsertWithWhereUniqueWithoutSellInput[]
  createMany?: Prisma.SellItemCreateManySellInputEnvelope
  set?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  disconnect?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  delete?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  connect?: Prisma.SellItemWhereUniqueInput | Prisma.SellItemWhereUniqueInput[]
  update?: Prisma.SellItemUpdateWithWhereUniqueWithoutSellInput | Prisma.SellItemUpdateWithWhereUniqueWithoutSellInput[]
  updateMany?: Prisma.SellItemUpdateManyWithWhereWithoutSellInput | Prisma.SellItemUpdateManyWithWhereWithoutSellInput[]
  deleteMany?: Prisma.SellItemScalarWhereInput | Prisma.SellItemScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type SellItemCreateWithoutProductInput = {
  id?: string
  quantity: number
  finalPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  sell: Prisma.SellCreateNestedOneWithoutCartInput
}

export type SellItemUncheckedCreateWithoutProductInput = {
  id?: string
  sellId: string
  quantity: number
  finalPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemCreateOrConnectWithoutProductInput = {
  where: Prisma.SellItemWhereUniqueInput
  create: Prisma.XOR<Prisma.SellItemCreateWithoutProductInput, Prisma.SellItemUncheckedCreateWithoutProductInput>
}

export type SellItemCreateManyProductInputEnvelope = {
  data: Prisma.SellItemCreateManyProductInput | Prisma.SellItemCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type SellItemUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.SellItemWhereUniqueInput
  update: Prisma.XOR<Prisma.SellItemUpdateWithoutProductInput, Prisma.SellItemUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.SellItemCreateWithoutProductInput, Prisma.SellItemUncheckedCreateWithoutProductInput>
}

export type SellItemUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.SellItemWhereUniqueInput
  data: Prisma.XOR<Prisma.SellItemUpdateWithoutProductInput, Prisma.SellItemUncheckedUpdateWithoutProductInput>
}

export type SellItemUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.SellItemScalarWhereInput
  data: Prisma.XOR<Prisma.SellItemUpdateManyMutationInput, Prisma.SellItemUncheckedUpdateManyWithoutProductInput>
}

export type SellItemScalarWhereInput = {
  AND?: Prisma.SellItemScalarWhereInput | Prisma.SellItemScalarWhereInput[]
  OR?: Prisma.SellItemScalarWhereInput[]
  NOT?: Prisma.SellItemScalarWhereInput | Prisma.SellItemScalarWhereInput[]
  id?: Prisma.UuidFilter<"SellItem"> | string
  sellId?: Prisma.UuidFilter<"SellItem"> | string
  productId?: Prisma.UuidFilter<"SellItem"> | string
  quantity?: Prisma.IntFilter<"SellItem"> | number
  finalPrice?: Prisma.DecimalFilter<"SellItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemCreateWithoutSellInput = {
  id?: string
  quantity: number
  finalPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  product: Prisma.ProductCreateNestedOneWithoutSellItemsInput
}

export type SellItemUncheckedCreateWithoutSellInput = {
  id?: string
  productId: string
  quantity: number
  finalPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemCreateOrConnectWithoutSellInput = {
  where: Prisma.SellItemWhereUniqueInput
  create: Prisma.XOR<Prisma.SellItemCreateWithoutSellInput, Prisma.SellItemUncheckedCreateWithoutSellInput>
}

export type SellItemCreateManySellInputEnvelope = {
  data: Prisma.SellItemCreateManySellInput | Prisma.SellItemCreateManySellInput[]
  skipDuplicates?: boolean
}

export type SellItemUpsertWithWhereUniqueWithoutSellInput = {
  where: Prisma.SellItemWhereUniqueInput
  update: Prisma.XOR<Prisma.SellItemUpdateWithoutSellInput, Prisma.SellItemUncheckedUpdateWithoutSellInput>
  create: Prisma.XOR<Prisma.SellItemCreateWithoutSellInput, Prisma.SellItemUncheckedCreateWithoutSellInput>
}

export type SellItemUpdateWithWhereUniqueWithoutSellInput = {
  where: Prisma.SellItemWhereUniqueInput
  data: Prisma.XOR<Prisma.SellItemUpdateWithoutSellInput, Prisma.SellItemUncheckedUpdateWithoutSellInput>
}

export type SellItemUpdateManyWithWhereWithoutSellInput = {
  where: Prisma.SellItemScalarWhereInput
  data: Prisma.XOR<Prisma.SellItemUpdateManyMutationInput, Prisma.SellItemUncheckedUpdateManyWithoutSellInput>
}

export type SellItemCreateManyProductInput = {
  id?: string
  sellId: string
  quantity: number
  finalPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  sell?: Prisma.SellUpdateOneRequiredWithoutCartNestedInput
}

export type SellItemUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sellId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sellId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemCreateManySellInput = {
  id?: string
  productId: string
  quantity: number
  finalPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemUpdateWithoutSellInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  product?: Prisma.ProductUpdateOneRequiredWithoutSellItemsNestedInput
}

export type SellItemUncheckedUpdateWithoutSellInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type SellItemUncheckedUpdateManyWithoutSellInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  finalPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}



export type SellItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sellId?: boolean
  productId?: boolean
  quantity?: boolean
  finalPrice?: boolean
  sell?: boolean | Prisma.SellDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sellItem"]>

export type SellItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sellId?: boolean
  productId?: boolean
  quantity?: boolean
  finalPrice?: boolean
  sell?: boolean | Prisma.SellDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sellItem"]>

export type SellItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sellId?: boolean
  productId?: boolean
  quantity?: boolean
  finalPrice?: boolean
  sell?: boolean | Prisma.SellDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sellItem"]>

export type SellItemSelectScalar = {
  id?: boolean
  sellId?: boolean
  productId?: boolean
  quantity?: boolean
  finalPrice?: boolean
}

export type SellItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sellId" | "productId" | "quantity" | "finalPrice", ExtArgs["result"]["sellItem"]>
export type SellItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sell?: boolean | Prisma.SellDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type SellItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sell?: boolean | Prisma.SellDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type SellItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sell?: boolean | Prisma.SellDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $SellItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SellItem"
  objects: {
    sell: Prisma.$SellPayload<ExtArgs>
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    sellId: string
    productId: string
    quantity: number
    finalPrice: runtime.Decimal
  }, ExtArgs["result"]["sellItem"]>
  composites: {}
}

export type SellItemGetPayload<S extends boolean | null | undefined | SellItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SellItemPayload, S>

export type SellItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SellItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SellItemCountAggregateInputType | true
  }

export interface SellItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SellItem'], meta: { name: 'SellItem' } }
  /**
   * Find zero or one SellItem that matches the filter.
   * @param {SellItemFindUniqueArgs} args - Arguments to find a SellItem
   * @example
   * // Get one SellItem
   * const sellItem = await prisma.sellItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SellItemFindUniqueArgs>(args: Prisma.SelectSubset<T, SellItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SellItemClient<runtime.Types.Result.GetResult<Prisma.$SellItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SellItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SellItemFindUniqueOrThrowArgs} args - Arguments to find a SellItem
   * @example
   * // Get one SellItem
   * const sellItem = await prisma.sellItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SellItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SellItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SellItemClient<runtime.Types.Result.GetResult<Prisma.$SellItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SellItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellItemFindFirstArgs} args - Arguments to find a SellItem
   * @example
   * // Get one SellItem
   * const sellItem = await prisma.sellItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SellItemFindFirstArgs>(args?: Prisma.SelectSubset<T, SellItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__SellItemClient<runtime.Types.Result.GetResult<Prisma.$SellItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SellItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellItemFindFirstOrThrowArgs} args - Arguments to find a SellItem
   * @example
   * // Get one SellItem
   * const sellItem = await prisma.sellItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SellItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SellItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SellItemClient<runtime.Types.Result.GetResult<Prisma.$SellItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SellItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SellItems
   * const sellItems = await prisma.sellItem.findMany()
   * 
   * // Get first 10 SellItems
   * const sellItems = await prisma.sellItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sellItemWithIdOnly = await prisma.sellItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SellItemFindManyArgs>(args?: Prisma.SelectSubset<T, SellItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SellItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SellItem.
   * @param {SellItemCreateArgs} args - Arguments to create a SellItem.
   * @example
   * // Create one SellItem
   * const SellItem = await prisma.sellItem.create({
   *   data: {
   *     // ... data to create a SellItem
   *   }
   * })
   * 
   */
  create<T extends SellItemCreateArgs>(args: Prisma.SelectSubset<T, SellItemCreateArgs<ExtArgs>>): Prisma.Prisma__SellItemClient<runtime.Types.Result.GetResult<Prisma.$SellItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SellItems.
   * @param {SellItemCreateManyArgs} args - Arguments to create many SellItems.
   * @example
   * // Create many SellItems
   * const sellItem = await prisma.sellItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SellItemCreateManyArgs>(args?: Prisma.SelectSubset<T, SellItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SellItems and returns the data saved in the database.
   * @param {SellItemCreateManyAndReturnArgs} args - Arguments to create many SellItems.
   * @example
   * // Create many SellItems
   * const sellItem = await prisma.sellItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SellItems and only return the `id`
   * const sellItemWithIdOnly = await prisma.sellItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SellItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SellItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SellItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SellItem.
   * @param {SellItemDeleteArgs} args - Arguments to delete one SellItem.
   * @example
   * // Delete one SellItem
   * const SellItem = await prisma.sellItem.delete({
   *   where: {
   *     // ... filter to delete one SellItem
   *   }
   * })
   * 
   */
  delete<T extends SellItemDeleteArgs>(args: Prisma.SelectSubset<T, SellItemDeleteArgs<ExtArgs>>): Prisma.Prisma__SellItemClient<runtime.Types.Result.GetResult<Prisma.$SellItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SellItem.
   * @param {SellItemUpdateArgs} args - Arguments to update one SellItem.
   * @example
   * // Update one SellItem
   * const sellItem = await prisma.sellItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SellItemUpdateArgs>(args: Prisma.SelectSubset<T, SellItemUpdateArgs<ExtArgs>>): Prisma.Prisma__SellItemClient<runtime.Types.Result.GetResult<Prisma.$SellItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SellItems.
   * @param {SellItemDeleteManyArgs} args - Arguments to filter SellItems to delete.
   * @example
   * // Delete a few SellItems
   * const { count } = await prisma.sellItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SellItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, SellItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SellItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SellItems
   * const sellItem = await prisma.sellItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SellItemUpdateManyArgs>(args: Prisma.SelectSubset<T, SellItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SellItems and returns the data updated in the database.
   * @param {SellItemUpdateManyAndReturnArgs} args - Arguments to update many SellItems.
   * @example
   * // Update many SellItems
   * const sellItem = await prisma.sellItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SellItems and only return the `id`
   * const sellItemWithIdOnly = await prisma.sellItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SellItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SellItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SellItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SellItem.
   * @param {SellItemUpsertArgs} args - Arguments to update or create a SellItem.
   * @example
   * // Update or create a SellItem
   * const sellItem = await prisma.sellItem.upsert({
   *   create: {
   *     // ... data to create a SellItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SellItem we want to update
   *   }
   * })
   */
  upsert<T extends SellItemUpsertArgs>(args: Prisma.SelectSubset<T, SellItemUpsertArgs<ExtArgs>>): Prisma.Prisma__SellItemClient<runtime.Types.Result.GetResult<Prisma.$SellItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SellItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellItemCountArgs} args - Arguments to filter SellItems to count.
   * @example
   * // Count the number of SellItems
   * const count = await prisma.sellItem.count({
   *   where: {
   *     // ... the filter for the SellItems we want to count
   *   }
   * })
  **/
  count<T extends SellItemCountArgs>(
    args?: Prisma.Subset<T, SellItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SellItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SellItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SellItemAggregateArgs>(args: Prisma.Subset<T, SellItemAggregateArgs>): Prisma.PrismaPromise<GetSellItemAggregateType<T>>

  /**
   * Group by SellItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SellItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SellItemGroupByArgs['orderBy'] }
      : { orderBy?: SellItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SellItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSellItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SellItem model
 */
readonly fields: SellItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SellItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SellItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sell<T extends Prisma.SellDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SellDefaultArgs<ExtArgs>>): Prisma.Prisma__SellClient<runtime.Types.Result.GetResult<Prisma.$SellPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SellItem model
 */
export interface SellItemFieldRefs {
  readonly id: Prisma.FieldRef<"SellItem", 'String'>
  readonly sellId: Prisma.FieldRef<"SellItem", 'String'>
  readonly productId: Prisma.FieldRef<"SellItem", 'String'>
  readonly quantity: Prisma.FieldRef<"SellItem", 'Int'>
  readonly finalPrice: Prisma.FieldRef<"SellItem", 'Decimal'>
}
    

// Custom InputTypes
/**
 * SellItem findUnique
 */
export type SellItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellItem
   */
  select?: Prisma.SellItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellItem
   */
  omit?: Prisma.SellItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellItemInclude<ExtArgs> | null
  /**
   * Filter, which SellItem to fetch.
   */
  where: Prisma.SellItemWhereUniqueInput
}

/**
 * SellItem findUniqueOrThrow
 */
export type SellItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellItem
   */
  select?: Prisma.SellItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellItem
   */
  omit?: Prisma.SellItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellItemInclude<ExtArgs> | null
  /**
   * Filter, which SellItem to fetch.
   */
  where: Prisma.SellItemWhereUniqueInput
}

/**
 * SellItem findFirst
 */
export type SellItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellItem
   */
  select?: Prisma.SellItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellItem
   */
  omit?: Prisma.SellItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellItemInclude<ExtArgs> | null
  /**
   * Filter, which SellItem to fetch.
   */
  where?: Prisma.SellItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SellItems to fetch.
   */
  orderBy?: Prisma.SellItemOrderByWithRelationInput | Prisma.SellItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SellItems.
   */
  cursor?: Prisma.SellItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SellItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SellItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SellItems.
   */
  distinct?: Prisma.SellItemScalarFieldEnum | Prisma.SellItemScalarFieldEnum[]
}

/**
 * SellItem findFirstOrThrow
 */
export type SellItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellItem
   */
  select?: Prisma.SellItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellItem
   */
  omit?: Prisma.SellItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellItemInclude<ExtArgs> | null
  /**
   * Filter, which SellItem to fetch.
   */
  where?: Prisma.SellItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SellItems to fetch.
   */
  orderBy?: Prisma.SellItemOrderByWithRelationInput | Prisma.SellItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SellItems.
   */
  cursor?: Prisma.SellItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SellItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SellItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SellItems.
   */
  distinct?: Prisma.SellItemScalarFieldEnum | Prisma.SellItemScalarFieldEnum[]
}

/**
 * SellItem findMany
 */
export type SellItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellItem
   */
  select?: Prisma.SellItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellItem
   */
  omit?: Prisma.SellItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellItemInclude<ExtArgs> | null
  /**
   * Filter, which SellItems to fetch.
   */
  where?: Prisma.SellItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SellItems to fetch.
   */
  orderBy?: Prisma.SellItemOrderByWithRelationInput | Prisma.SellItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SellItems.
   */
  cursor?: Prisma.SellItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SellItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SellItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SellItems.
   */
  distinct?: Prisma.SellItemScalarFieldEnum | Prisma.SellItemScalarFieldEnum[]
}

/**
 * SellItem create
 */
export type SellItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellItem
   */
  select?: Prisma.SellItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellItem
   */
  omit?: Prisma.SellItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellItemInclude<ExtArgs> | null
  /**
   * The data needed to create a SellItem.
   */
  data: Prisma.XOR<Prisma.SellItemCreateInput, Prisma.SellItemUncheckedCreateInput>
}

/**
 * SellItem createMany
 */
export type SellItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SellItems.
   */
  data: Prisma.SellItemCreateManyInput | Prisma.SellItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SellItem createManyAndReturn
 */
export type SellItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellItem
   */
  select?: Prisma.SellItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SellItem
   */
  omit?: Prisma.SellItemOmit<ExtArgs> | null
  /**
   * The data used to create many SellItems.
   */
  data: Prisma.SellItemCreateManyInput | Prisma.SellItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SellItem update
 */
export type SellItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellItem
   */
  select?: Prisma.SellItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellItem
   */
  omit?: Prisma.SellItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellItemInclude<ExtArgs> | null
  /**
   * The data needed to update a SellItem.
   */
  data: Prisma.XOR<Prisma.SellItemUpdateInput, Prisma.SellItemUncheckedUpdateInput>
  /**
   * Choose, which SellItem to update.
   */
  where: Prisma.SellItemWhereUniqueInput
}

/**
 * SellItem updateMany
 */
export type SellItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SellItems.
   */
  data: Prisma.XOR<Prisma.SellItemUpdateManyMutationInput, Prisma.SellItemUncheckedUpdateManyInput>
  /**
   * Filter which SellItems to update
   */
  where?: Prisma.SellItemWhereInput
  /**
   * Limit how many SellItems to update.
   */
  limit?: number
}

/**
 * SellItem updateManyAndReturn
 */
export type SellItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellItem
   */
  select?: Prisma.SellItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SellItem
   */
  omit?: Prisma.SellItemOmit<ExtArgs> | null
  /**
   * The data used to update SellItems.
   */
  data: Prisma.XOR<Prisma.SellItemUpdateManyMutationInput, Prisma.SellItemUncheckedUpdateManyInput>
  /**
   * Filter which SellItems to update
   */
  where?: Prisma.SellItemWhereInput
  /**
   * Limit how many SellItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SellItem upsert
 */
export type SellItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellItem
   */
  select?: Prisma.SellItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellItem
   */
  omit?: Prisma.SellItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellItemInclude<ExtArgs> | null
  /**
   * The filter to search for the SellItem to update in case it exists.
   */
  where: Prisma.SellItemWhereUniqueInput
  /**
   * In case the SellItem found by the `where` argument doesn't exist, create a new SellItem with this data.
   */
  create: Prisma.XOR<Prisma.SellItemCreateInput, Prisma.SellItemUncheckedCreateInput>
  /**
   * In case the SellItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SellItemUpdateInput, Prisma.SellItemUncheckedUpdateInput>
}

/**
 * SellItem delete
 */
export type SellItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellItem
   */
  select?: Prisma.SellItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellItem
   */
  omit?: Prisma.SellItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellItemInclude<ExtArgs> | null
  /**
   * Filter which SellItem to delete.
   */
  where: Prisma.SellItemWhereUniqueInput
}

/**
 * SellItem deleteMany
 */
export type SellItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SellItems to delete
   */
  where?: Prisma.SellItemWhereInput
  /**
   * Limit how many SellItems to delete.
   */
  limit?: number
}

/**
 * SellItem without action
 */
export type SellItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellItem
   */
  select?: Prisma.SellItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellItem
   */
  omit?: Prisma.SellItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellItemInclude<ExtArgs> | null
}
