
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Category: 'Category',
  Country: 'Country',
  CountryState: 'CountryState',
  McpOAuthClient: 'McpOAuthClient',
  McpOAuthCode: 'McpOAuthCode',
  Product: 'Product',
  Sell: 'Sell',
  SellItem: 'SellItem',
  Stock: 'Stock',
  Store: 'Store',
  Subcategory: 'Subcategory',
  User: 'User',
  UserSession: 'UserSession'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  sku: 'sku',
  images: 'images',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const CountryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  flag: 'flag',
  code3: 'code3',
  code2: 'code2',
  tz: 'tz',
  currency3: 'currency3',
  currencySymbol: 'currencySymbol',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CountryScalarFieldEnum = (typeof CountryScalarFieldEnum)[keyof typeof CountryScalarFieldEnum]


export const CountryStateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  countryId: 'countryId',
  subdivisionCode: 'subdivisionCode',
  tz: 'tz',
  flag: 'flag',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CountryStateScalarFieldEnum = (typeof CountryStateScalarFieldEnum)[keyof typeof CountryStateScalarFieldEnum]


export const McpOAuthClientScalarFieldEnum = {
  id: 'id',
  clientId: 'clientId',
  clientName: 'clientName',
  redirectUris: 'redirectUris',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type McpOAuthClientScalarFieldEnum = (typeof McpOAuthClientScalarFieldEnum)[keyof typeof McpOAuthClientScalarFieldEnum]


export const McpOAuthCodeScalarFieldEnum = {
  id: 'id',
  code: 'code',
  clientId: 'clientId',
  userId: 'userId',
  redirectUri: 'redirectUri',
  codeChallenge: 'codeChallenge',
  codeChallengeMethod: 'codeChallengeMethod',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
} as const

export type McpOAuthCodeScalarFieldEnum = (typeof McpOAuthCodeScalarFieldEnum)[keyof typeof McpOAuthCodeScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  subcategoryId: 'subcategoryId',
  sku: 'sku',
  description: 'description',
  mrp: 'mrp',
  mop: 'mop',
  images: 'images',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const SellScalarFieldEnum = {
  id: 'id',
  storeId: 'storeId',
  customerId: 'customerId',
  staffId: 'staffId',
  finalSellPrice: 'finalSellPrice',
  transactionDate: 'transactionDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SellScalarFieldEnum = (typeof SellScalarFieldEnum)[keyof typeof SellScalarFieldEnum]


export const SellItemScalarFieldEnum = {
  id: 'id',
  sellId: 'sellId',
  productId: 'productId',
  quantity: 'quantity',
  finalPrice: 'finalPrice'
} as const

export type SellItemScalarFieldEnum = (typeof SellItemScalarFieldEnum)[keyof typeof SellItemScalarFieldEnum]


export const StockScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  storeId: 'storeId',
  quantity: 'quantity',
  minThreshold: 'minThreshold',
  lastUpdated: 'lastUpdated',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StockScalarFieldEnum = (typeof StockScalarFieldEnum)[keyof typeof StockScalarFieldEnum]


export const StoreScalarFieldEnum = {
  id: 'id',
  name: 'name',
  storeCode: 'storeCode',
  addressLine1: 'addressLine1',
  zip: 'zip',
  stateId: 'stateId',
  countryId: 'countryId',
  managerId: 'managerId',
  staffIds: 'staffIds',
  locationMapLink: 'locationMapLink',
  images: 'images',
  description: 'description',
  yearlyUpkeep: 'yearlyUpkeep',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StoreScalarFieldEnum = (typeof StoreScalarFieldEnum)[keyof typeof StoreScalarFieldEnum]


export const SubcategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  categoryId: 'categoryId',
  sku: 'sku',
  images: 'images',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SubcategoryScalarFieldEnum = (typeof SubcategoryScalarFieldEnum)[keyof typeof SubcategoryScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  firstName: 'firstName',
  lastName: 'lastName',
  password: 'password',
  profileImage: 'profileImage',
  role: 'role',
  salary: 'salary',
  countryId: 'countryId',
  stateId: 'stateId',
  address: 'address',
  zip: 'zip',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const UserSessionScalarFieldEnum = {
  id: 'id',
  ip: 'ip',
  userAgent: 'userAgent',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserSessionScalarFieldEnum = (typeof UserSessionScalarFieldEnum)[keyof typeof UserSessionScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

